import { GraduationQuizQuestion } from '@/data/graduationContent';

// ============================================================================
// TOPIC 5: Statisztika, valószínűségszámítás
// ============================================================================

// --- 1. Leíró statisztika és mutatószámok (g-descriptive-stats, g-data-representation, g-large-datasets) ---
export const quizStatsEasy: GraduationQuizQuestion[] = [
  { id: "q-st-e-1", question: "Mennyi a $2, 4, 6, 8, 10$ számsorozat átlaga?", options: ["6", "5", "7", "4"], correctAnswer: 0, explanation: "$\\frac{2+4+6+8+10}{5} = \\frac{30}{5} = 6$." },
  { id: "q-st-e-2", question: "Mi a mediánja az $1, 3, 5, 7, 9$ rendezett számsorozatnak?", options: ["5", "3", "7", "4.5"], correctAnswer: 0, explanation: "A 3. (középső) elem az 5." },
  { id: "q-st-e-3", question: "Mi a módusza a $2, 3, 3, 4, 5, 5, 5, 6$ adatsornak?", options: ["5", "3", "4", "6"], correctAnswer: 0, explanation: "Az 5-ös fordul elő a legtöbbször (3-szor)." },
  { id: "q-st-e-4", question: "Mennyi az adatok terjedelme, ha a legkisebb adat 12, a legnagyobb 45?", options: ["33", "57", "28.5", "45"], correctAnswer: 0, explanation: "Terjedelem: $45 - 12 = 33$." },
  { id: "q-st-e-5", question: "Mennyi a mediánja a $2, 4, 6, 8$ páros elemszámú adatsornak?", options: ["5", "4", "6", "4.5"], correctAnswer: 0, explanation: "Páros elemszámnál a két középső elem (4 és 6) átlaga: $(4+6)/2 = 5$." },
  { id: "q-st-e-6", question: "Melyik diagramtípus alkalmas leginkább egy változó részarányainak (százalékos megoszlásának) ábrázolására?", options: ["Kördiagram (szektor-diagram)", "Oszlopdiagram", "Vonaldiagram", "Histogram"], correctAnswer: 0, explanation: "A kördiagram a teljes $100\\%$-os megoszlást ábrázolja szemléletesen." },
  { id: "q-st-e-7", question: "Melyik diagramtípus mutatja legszemléletesebben az adatok időbeli változását (pl. hőmérséklet alakulása)?", options: ["Vonaldiagram", "Kördiagram", "Sávdiagram", "Boxplot"], correctAnswer: 0, explanation: "Időbeli lefolyást a vonaldiagram ábrázol." },
  { id: "q-st-e-8", question: "Mit jelent a minta elemszáma ($n$)?", options: ["A megfigyelt vagy megkérdezett egyedek/adatok összes számát", "A leggyakoribb értéket", "Az átlagot", "Az adatok szórását"], correctAnswer: 0, explanation: "A minta elemszáma $n$." },
  { id: "q-st-e-9", question: "Mennyi a $10, 10, 10, 10$ adatsor terjedelme?", options: ["0", "10", "40", "1"], correctAnswer: 0, explanation: "$10 - 10 = 0$." },
  { id: "q-st-e-10", question: "Ha az adatok összege 150 és az elemek száma 15, mennyi az átlag?", options: ["10", "15", "150", "5"], correctAnswer: 0, explanation: "$150 / 15 = 10$." }
];

export const quizStatsMedium: GraduationQuizQuestion[] = [
  { id: "q-st-m-1", question: "Egy dolgozat eredményei: 5 darab 5-ös, 3 darab 4-es, 2 darab 3-as. Mennyi a súlyozott átlag?", options: ["4.3", "4.0", "4.5", "4.1"], correctAnswer: 0, explanation: "$\\frac{5(5) + 3(4) + 2(3)}{10} = \\frac{25 + 12 + 6}{10} = \\frac{43}{10} = 4,3$." },
  { id: "q-st-m-2", question: "Mi a szórása a $3, 3, 3, 3$ adatsornak?", options: ["0", "3", "1", "Nincs szórása"], correctAnswer: 0, explanation: "Minden adat megegyezik az átlaggal, az eltérés 0." },
  { id: "q-st-m-3", question: "Mennyi a $1, 2, 3, 4, 5$ adatsor átlagos abszolút eltérése az átlagtól ($\\bar{x} = 3$)?", options: ["1.2", "1.5", "1.0", "2.0"], correctAnswer: 0, explanation: "Eltérések: $2, 1, 0, 1, 2 \\Rightarrow$ átlaguk $\\frac{6}{5} = 1,2$." },
  { id: "q-st-m-4", question: "Hány mutatót tartalmaz a dobozábra (boxplot) 5-számos összefoglalója?", options: ["Min, Q1 (alsó kvartilis), Q2 (medián), Q3 (felső kvartilis), Max", "Átlag, Szórás, Módusz, Terjedelem", "Q1, Q2, Q3", "Min és Max"], correctAnswer: 0, explanation: "A 5-számos összefoglaló: Min, Q1, Q2 (medián), Q3, Max." },
  { id: "q-st-m-5", question: "Mit mér az interkvartilis terjedelem ($IQR$)?", options: ["A középső $50\\%$ szóródását: $IQR = Q_3 - Q_1$", "A legnagyobb és legkisebb elem különbségét", "Az átlagot", "A szórás négyzetét"], correctAnswer: 0, explanation: "$IQR = Q_3 - Q_1$ a középső adatok terjedelme." },
  { id: "q-st-m-6", question: "Ha az adatsorban egy rendkívül nagy kiugró adat (outlier) jelenik meg, melyik mutatót változtatja meg a legjobban?", options: ["Az átlagot (a medián és módusz robusztusabb)", "A mediánt", "A móduszt", "Egyiket sem"], correctAnswer: 0, explanation: "Az átlag érzékeny a kiugró értékekre, a medián robusztus." },
  { id: "q-st-m-7", question: "Mennyi a $2, 4, 4, 4, 6, 8, 14$ adatsor alsó kvartilise ($Q_1$)?", options: ["4", "2", "6", "8"], correctAnswer: 0, explanation: "Az alsó fele $\\{2, 4, 4\\}$, melynek mediánja 4." },
  { id: "q-st-m-8", question: "Milyen eloszlást mutat a hisztogram, ha a jobb oldali 'farka' hosszabb (jobbra ferde)?", options: ["Pozitívan ferde (jobbra nyújtott, átlag > medián)", "Szimmetrikus", "Negatívan ferde", "Egyenletes"], correctAnswer: 0, explanation: "Jobbra ferde eloszlásnál az átlag nagyobb a mediánnál." },
  { id: "q-st-m-9", question: "Számítsd ki a $2, 4, 6$ adatsor tapasztalati szórásnégyzetét (varianciáját)! Az átlag $\\bar{x} = 4$.", options: ["$8/3 \\approx 2.67$", "4", "2", "8"], correctAnswer: 0, explanation: "Eltérés-négyzetek: $(2-4)^2 + (4-4)^2 + (6-4)^2 = 4 + 0 + 4 = 8 \\Rightarrow 8/3$." },
  { id: "q-st-m-10", question: "Melyik adatábrázolás mutatja a folytonos adatok oszlopokba (osztályokba) sorolt gyakoriságát?", options: ["Hisztogram", "Kördiagram", "Vonaldiagram", "Fa-diagram"], correctAnswer: 0, explanation: "A hisztogram az osztályokba sorolt adatok gyakorisági oszlopdiagramja." }
];

export const quizStatsHard: GraduationQuizQuestion[] = [
  { id: "q-st-h-1", question: "Egy 10 elemű mintában a korrelációs együttható $r = 0,95$. Mit jelent ez a két változó között?", options: ["Igen erős pozitív lineáris kapcsolat van közöttük", "Nincs kapcsolat", "Negatív kapcsolat van", "Ok-okozati összefüggést bizonyít"], correctAnswer: 0, explanation: "$r \\approx 1$ erős pozitív lineáris korrelációt mutat." },
  { id: "q-st-h-2", question: "Mi a korreláció és a kauzalitás (ok-okozat) közötti különbség?", options: ["A korreláció csak együttmozgást mér, az ok-okozati kapcsolatot nem bizonyítja önmagában!", "Ugyanazt jelentik", "A korreláció mindig ok-okozatot jelent", "Nincs kapcsolat"], correctAnswer: 0, explanation: "Correlation does not imply causation." },
  { id: "q-st-h-3", question: "A Steiner-tétel szerint melyik középértékre minimális a négyzetes eltérések összege: $\\sum (x_i - c)^2$?", options: ["A számtani átlagra ($c = \\bar{x}$)", "A mediánra", "A móduszra", "A mértani középre"], correctAnswer: 0, explanation: "A számtani átlag minimalizálja a négyzetes eltérésösszeget." },
  { id: "q-st-h-4", question: "Melyik mutatót minimalizálja az abszolút eltérések összege: $\\sum |x_i - c|$?", options: ["A mediánt ($c = \\text{Me}$)", "A számtani átlagot", "A móduszt", "A terjedelmet"], correctAnswer: 0, explanation: "A medián minimalizálja az abszolút eltérések összegét." },
  { id: "q-st-h-5", question: "Mi a korrigált tapasztalati szórásnégyzet ($s^2$) képlete n elemű mintára?", options: ["$s^2 = \\frac{1}{n-1} \\sum_{i=1}^n (x_i - \\bar{x})^2$", "$s^2 = \\frac{1}{n} \\sum (x_i - \\bar{x})^2$", "$s = \\sqrt{n}$", "$s = \\bar{x}/n$"], correctAnswer: 0, explanation: "A korrigált mintaszórásnál $n-1$-gyel osztunk a torzatlanságért." },
  { id: "q-st-h-6", question: "Mi a Pearson-féle lineáris korrelációs együttható képlete ($r_{x, y}$)?", options: ["$r = \\frac{\\text{Cov}(X, Y)}{\\sigma_X \\sigma_Y}$", "$r = \\text{Cov}(X, Y)$", "$r = \\sigma_X / \\sigma_Y$", "$r = \\bar{X} \\cdot \\bar{Y}$"], correctAnswer: 0, explanation: "A kovariancia osztva a két szórás szorzatával." },
  { id: "q-st-h-7", question: "Milyen határok közé esik a Pearson-féle korrelációs együttható ($r$)?", options: ["$[-1, 1]$", "$[0, 1]$", "$(-\\infty, \\infty)$", "$[-100, 100]$"], correctAnswer: 0, explanation: "$-1 \\le r \\le 1$." },
  { id: "q-st-h-8", question: "Mi a regressziós egyenes ($y = ax + b$) legkisebb négyzetek módszerével történő meghatározásának lényege?", options: ["A mért pontok és az egyenes közötti függőleges eltérésnégyzetek összegének minimalizálása", "Pontos illeszkedés minden pontra", "A pontok összekötése töröttvonallal", "A vízszintes távolságok összegzése"], correctAnswer: 0, explanation: "Legkisebb négyzetek elve (OLS)." },
  { id: "q-st-h-9", question: "Standardizálás (Z-transzformáció): $Z = \\frac{X - \\mu}{\\sigma}$. Mennyi a Z változó átlaga és szórása?", options: ["Átlaga 0, szórása 1", "Átlaga 1, szórása 0", "Átlaga $\\mu$, szórása $\\sigma$", "Nincs szórása"], correctAnswer: 0, explanation: "Standardizálás után az átlag 0, a szórás 1 lesz." },
  { id: "q-st-h-10", question: "Mi a relatív szórás (variációs koefficiens, $V$)?", options: ["$V = \\frac{\\sigma}{\\bar{x}} \\cdot 100\\%$", "$V = \\sigma - \\bar{x}$", "$V = \\sigma^2$", "$V = \\bar{x}/\\sigma$"], correctAnswer: 0, explanation: "A szórás és az átlag hányadosa százalékban megadva." }
];

// --- 2. Valószínűségszámítás (g-probability) ---
export const quizProbEasy: GraduationQuizQuestion[] = [
  { id: "q-pr-e-1", question: "Egy szabályos dobókockával dobunk. Mi a valószínűsége, hogy páros számot dobunk?", options: ["1/2 (50%)", "1/6", "1/3", "2/3"], correctAnswer: 0, explanation: "Kedvező: 2, 4, 6 (3 db). Összes: 6. $P = 3/6 = 1/2$." },
  { id: "q-pr-e-2", question: "Egy érmével kétszer dobunk. Mi a valószínűsége, hogy mindkét dobás Fej lesz?", options: ["1/4 (25%)", "1/2 (50%)", "3/4", "1/8"], correctAnswer: 0, explanation: "Összesen 4 lehetőség (FF, FI, IF, II), ebből 1 az FF: $P = 1/4$." },
  { id: "q-pr-e-3", question: "Mi a biztos esemény valószínűsége?", options: ["1 (100%)", "0", "0.5", "Végtelen"], correctAnswer: 0, explanation: "Biztos esemény valószínűsége 1." },
  { id: "q-pr-e-4", question: "Mi a lehetetlen esemény valószínűsége?", options: ["0", "1", "-1", "0.5"], correctAnswer: 0, explanation: "Lehetetlen esemény valószínűsége 0." },
  { id: "q-pr-e-5", question: "Egy urnában 4 piros és 6 kék golyó van. Húzatunk egyet. Mi a valószínűsége, hogy pirosat húzunk?", options: ["4/10 = 2/5 (40%)", "6/10 = 3/5", "4/6", "1/4"], correctAnswer: 0, explanation: "Kedvező: 4, Összes: 10 $\\Rightarrow P = 4/10 = 40\\%$." },
  { id: "q-pr-e-6", question: "Ha $P(A) = 0.3$, mennyi a komplementer esemény valószínűsége ($P(\\bar{A})$)?", options: ["0.7 (70%)", "0.3", "0.5", "0.0"], correctAnswer: 0, explanation: "$P(\\bar{A}) = 1 - 0.3 = 0.7$." },
  { id: "q-pr-e-7", question: "Egy dobókockával dobva mi a valószínűsége, hogy 6-ost dobunk?", options: ["1/6", "1/2", "1", "0"], correctAnswer: 0, explanation: "1 kedvező kimenetel a 6-ból: $1/6$." },
  { id: "q-pr-e-8", question: "Melyik határok közé esik tetszőleges esemény valószínűsége?", options: ["$[0, 1]$", "$[-1, 1]$", "$[0, \\infty)$", "$[-100, 100]$"], correctAnswer: 0, explanation: "$0 \\le P(A) \\le 1$." },
  { id: "q-pr-e-9", question: "Milyen képlettel számolható a Laplace-féle klasszikus valószínűség?", options: ["$P(A) = \\frac{k}{n} = \\frac{\\text{Kedvező események}}{\\text{Összes esemény}}$", "$P(A) = k \\cdot n$", "$P(A) = n - k$", "$P(A) = k^n$"], correctAnswer: 0, explanation: "Klasszikus valószínűségi mező képlete." },
  { id: "q-pr-e-10", question: "Egy pakli 52 lapos kártyából húzunk 1 lapot. Mi a valószínűsége, hogy Ászt húzunk?", options: ["4/52 = 1/13", "1/52", "13/52", "4/13"], correctAnswer: 0, explanation: "4 Ász van a 52 lapban: $4/52 = 1/13$." }
];

export const quizProbMedium: GraduationQuizQuestion[] = [
  { id: "q-pr-m-1", question: "Két dobókockával dobunk egyszerre. Mi a valószínűsége, hogy a dobott számok összege 7 lesz?", options: ["6/36 = 1/6", "5/36", "7/36", "1/12"], correctAnswer: 0, explanation: "Kedvező párok: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) -> 6 db. $P = 6/36 = 1/6$." },
  { id: "q-pr-m-2", question: "Két független esemény valószínűsége $P(A) = 0.4$ és $P(B) = 0.5$. Mennyi az együttes bekövetkezésük valószínűsége ($P(A \\cap B)$)?", options: ["0.2", "0.9", "0.1", "0.5"], correctAnswer: 0, explanation: "Függetlenségnél $P(A \\cap B) = P(A) \\cdot P(B) = 0.4 \\cdot 0.5 = 0.2$." },
  { id: "q-pr-m-3", question: "Egy pakli 52 lapos kártyából egyet húzunk. Mi a valószínűsége, hogy Ászt VAGY Kőrt húzunk?", options: ["16/52 = 4/13", "17/52", "13/52", "4/52"], correctAnswer: 0, explanation: "$P(A \\cup B) = 4/52 + 13/52 - 1/52 = 16/52 = 4/13$." },
  { id: "q-pr-m-4", question: "Valószínűségi változó várható értéke $E(X) = 4$. Ha $Y = 3X + 2$, mennyi $E(Y)$?", options: ["14", "12", "10", "16"], correctAnswer: 0, explanation: "$E(3X + 2) = 3 E(X) + 2 = 3(4) + 2 = 14$." },
  { id: "q-pr-m-5", question: "Mennyi annak a valószínűsége, hogy egy szabályos érmével 4 dobásból pontosan 2-szer kapunk Fejet (Binomiális eloszlás)?", options: ["6/16 = 3/8 (37.5%)", "1/2", "1/4", "4/16"], correctAnswer: 0, explanation: "$\\binom{4}{2} (0.5)^2 (0.5)^2 = 6 \\cdot 1/16 = 3/8$." },
  { id: "q-pr-m-6", question: "Egy teszten 5 feleletválasztós kérdés van, mindegyiknél 4 opcióból 1 helyes. Mi a valószínűsége, hogy tippelve mind az 5 helyes lesz?", options: ["$(1/4)^5 = 1/1024$", "$5/4$", "$1/20$", "$1/5$"], correctAnswer: 0, explanation: "Független tippelések szorzata: $(1/4)^5 = 1/1024$." },
  { id: "q-pr-m-7", question: "Egy teszten 5 kérdésből mi a valószínűsége, hogy legalább 1-et eltalálunk tippelve?", options: ["$1 - (3/4)^5 = 1 - 243/1024 = 781/1024$", "$(1/4)^5$", "3/4", "1/2"], correctAnswer: 0, explanation: "Komplementer esemény: egyet sem találunk el ($(3/4)^5$). $P = 1 - (3/4)^5$." },
  { id: "q-pr-m-8", question: "Ha $P(A) = 0.6, P(B) = 0.5$ és $P(A \\cap B) = 0.3$, független-e a két esemény?", options: ["Igen, mert $P(A) \\cdot P(B) = 0.6 \\cdot 0.5 = 0.3 = P(A \\cap B)$", "Nem függetlenek", "Kizárják egymást", "Nem eldönthető"], correctAnswer: 0, explanation: "$P(A \\cap B) = P(A) \\cdot P(B)$ teljesül, így függetlenek." },
  { id: "q-pr-m-9", question: "Hányféleképpen húzható ki 5 lottószám a 90-ből?", options: ["$\\binom{90}{5} = 43\\ 949\\ 268$", "$90^5$", "$90! / 85!$", "5!"], correctAnswer: 0, explanation: "Kombináció ismétlés nélkül: $\\binom{90}{5}$." },
  { id: "q-pr-m-10", question: "Mi a különbség a visszatevéses és visszatevés nélküli mintavétel között?", options: ["Visszatevésesnél a kísérletek függetlenek (binomiális eloszlás), visszatevés nélkül függőek (hipermértani eloszlás)", "Nincs különbség", "Visszatevés nélkül független", "Csak a mintanagyság számít"], correctAnswer: 0, explanation: "Ez a függetlenség alapkérdése mintavételnél." }
];

export const quizProbHard: GraduationQuizQuestion[] = [
  { id: "q-pr-h-1", question: "A termékek $60\\%$-át az A gép, $40\\%$-át a B gép gyártja. Selejtarány: A=2%, B=5%. Egy kiválasztott termék selejtes. Mi a valószínűsége, hogy a B gép gyártotta (Bayes-tétel)?", options: ["20/32 = 62.5%", "50%", "40%", "2/3"], correctAnswer: 0, explanation: "$P(S) = 0.6(0.02) + 0.4(0.05) = 0.032$. Bayes: $P(B \\mid S) = 0.020 / 0.032 = 20/32 = 62,5\\%$." },
  { id: "q-pr-h-2", question: "Mekkora a szórása egy $n = 100, p = 0.3$ paraméterű binomiális eloszlású valószínűségi változónak ($\\sigma = \\sqrt{n p (1-p)}$)?", options: ["$\\sqrt{21} \\approx 4.58$", "21", "30", "4.2"], correctAnswer: 0, explanation: "Variancia $= 100 \\cdot 0.3 \\cdot 0.7 = 21 \\Rightarrow \\sigma = \\sqrt{21} \\approx 4.58$." },
  { id: "q-pr-h-3", question: "Mennyi az $X$ valószínűségi változó varianciája, ha $E(X) = 5$ és $E(X^2) = 29$ ($Var(X) = E(X^2) - (E(X))^2$)?", options: ["4", "24", "19", "2"], correctAnswer: 0, explanation: "$Var(X) = 29 - 5^2 = 29 - 25 = 4$." },
  { id: "q-pr-h-4", question: "Milyen állítást tesz a Csebisev-egyenlőtlenség tetszőleges valószínűségi változóra a $\\mu$-től való $k\\sigma$ eltérésre vonatkozóan?", options: ["$P(|X - \\mu| \\ge k\\sigma) \\le \\frac{1}{k^2}$", "$P(|X - \\mu| \\ge k\\sigma) = 0$", "Normalitást feltételez", "Csak folytonos változókra érvényes"], correctAnswer: 0, explanation: "Csebisev-egyenlőtlenség $k$ szórásnyi eltérésre." },
  { id: "q-pr-h-5", question: "Standard normális eloszlás $Z \\sim N(0, 1)$ esetén a központi 68%-os valószínűségi tartomány melyik intervallumba esik?", options: ["$[-1, 1]$", "$[-2, 2]$", "$[-3, 3]$", "$[0, 1]$"], correctAnswer: 0, explanation: "Az 1-szórásos szabály normális eloszlásnál $\\approx 68.3\\%$." },
  { id: "q-pr-h-6", question: "Hányféleképpen ülhet le 6 ember egy kerek asztal köré, ha a forgatással egymásba vihető ültetések azonosnak számítanak (Ciklikus permutáció)?", options: ["120 (5!)", "720 (6!)", "36", "64"], correctAnswer: 0, explanation: "Ciklikus permutációk: $(n-1)! = 5! = 120$." },
  { id: "q-pr-h-7", question: "Mennyi annak a valószínűsége, hogy 5 dobókockával dobva mind az 5 kockán különböző szám szerepel?", options: ["720 / 7776 ≈ 9.26%", "1/6", "5/6", "1/36"], correctAnswer: 0, explanation: "Kedvező: $6 \\cdot 5 \\cdot 4 \\cdot 3 \\cdot 2 = 720$. Összes: $6^5 = 7776$. $P = 720/7776 \\approx 9.26\\%$." },
  { id: "q-pr-h-8", question: "Mi a hipermértani eloszlás feltétele?", options: ["Visszatevés nélküli mintavétel véges sok elemet tartalmazó populációból", "Visszatevéses mintavétel", "Független kísérletek végtelen sora", "Folytonos mérések"], correctAnswer: 0, explanation: "Hipermértani eloszlás a visszatevés nélküli mintavételnél." },
  { id: "q-pr-h-9", question: "Ha $A$ és $B$ független események, $P(A) = 0.5$ és $P(B) = 0.4$, mennyi $P(A \\cup B)$?", options: ["0.7", "0.9", "0.2", "0.5"], correctAnswer: 0, explanation: "$P(A \\cup B) = 0.5 + 0.4 - (0.5 \\cdot 0.4) = 0.9 - 0.2 = 0.7$." },
  { id: "q-pr-h-10", question: "Mit állít a Központi Határeloszlás-tétel (CLT)?", options: ["Független, azonos eloszlású valószínűségi változók összegének (vagy átlagának) eloszlása $n \\to \\infty$ esetén a normális eloszláshoz tart", "Minden eloszlás binomiális", "A szórás mindig 1", "Az átlagok mindig 0-k"], correctAnswer: 0, explanation: "A valószínűségszámítás egyik legfontosabb tétele (Central Limit Theorem)." }
];

// Map containing dedicated quizzes for every subtopic in Statisztika, valószínűségszámítás
export const statisztikaValoszinusegQuizzes: Record<string, { easy: GraduationQuizQuestion[]; medium: GraduationQuizQuestion[]; hard: GraduationQuizQuestion[] }> = {
  'g-descriptive-stats': { easy: quizStatsEasy, medium: quizStatsMedium, hard: quizStatsHard },
  'g-data-representation': { easy: quizStatsEasy, medium: quizStatsMedium, hard: quizStatsHard },
  'g-large-datasets': { easy: quizStatsEasy, medium: quizStatsMedium, hard: quizStatsHard },
  'g-probability': { easy: quizProbEasy, medium: quizProbMedium, hard: quizProbHard }
};
