export const CONTENT_AREAS = [
  {
    id: 'M',
    name: 'Mennyiségek, számok, műveletek',
    color: '#2563eb',
    subs: {
      '1.1.1': 'számegyenes',
      '1.1.2': 'intervallum',
      '1.1.3': 'számok felbontása, helyi érték',
      '1.1.4': 'törtek (közönséges és tizedes törtek, ekvivalencia, összehasonlítás, egyszerűsítés, vizuális megjelenítés)',
      '1.2.1': 'műveletsor (felírás, elvégzés, kerekítés)',
      '1.2.2': 'százalékérték kiszámítása, százalékos arány megfeleltetése',
      '1.2.3': 'arányszámítás – 1-hez viszonyítva',
      '1.2.4': 'méretarány 1-hez viszonyítva',
      '1.2.5': 'számítások geometriai alakzatokkal (kerület, terület, felszín, térfogat)',
      '1.2.6': 'behelyettesítés átrendezés nélkül',
      '1.3.1': 'skála (leolvasás, berajzolás)',
      '1.3.2': 'mennyiségek összehasonlítása',
      '1.3.3': 'mértékegység-átváltás',
      '1.3.4': 'számolás idővel (időzóna is)',
      '1.4.1': 'közös osztó, közös többszörös',
      '1.4.2': 'maradékok vizsgálata, oszthatósági szabályok',
    },
  },
  {
    id: 'H',
    name: 'Hozzárendelések, összefüggések',
    color: '#0891b2',
    subs: {
      '2.1.1': 'összefüggések leolvasása (érték, meredekség, folytatás, értelmezés)',
      '2.1.2': 'összefüggések ábrázolása (grafikonon, gráfon), ábrázolás vizsgálata',
      '2.1.3': 'hozzárendelési szabály (megadás, alkalmazás, paraméterezés)',
      '2.1.4': 'változók közötti kapcsolat',
      '2.2.1': 'számok, mennyiségek aránya (nem 1-hez viszonyítva)',
      '2.2.2': 'méretarány nem 1-hez viszonyítva',
      '2.2.3': 'százalékalap és százalékláb kiszámítása',
      '2.3.1': 'formulákkal, képletekkel végzett műveletek',
      '2.3.2': 'egyenlet, egyenlőtlenség (felírás, megoldás)',
      '2.4.1': 'szabálykövetés – következő elem meghatározása',
      '2.4.2': 'szabálykövetés – adott sorszámú elem, elem sorszáma',
      '2.4.3': 'sorozat elemeinek összege',
    },
  },
  {
    id: 'A',
    name: 'Alakzatok, tájékozódás',
    color: '#16a34a',
    subs: {
      '3.1.1': 'geometriai tulajdonságok (négyzet átlója, háromszög szögei, sokszögek)',
      '3.1.2': 'síkbeli transzformációk: egybevágóság (tengelyes és középpontos tükrözés, eltolás, elforgatás), szimmetria',
      '3.1.3': 'síkidomok kerülete, területe (becslés, átdarabolás, lefedés)',
      '3.2.1': 'test ábrázolása (nézet, háló, alkotóelemek)',
      '3.2.2': 'befoglaló test',
      '3.2.3': 'térbeli transzformációk',
      '3.2.4': 'testek paraméterei és felszíne, térfogata',
      '3.3.1': 'irányok, égtájak',
      '3.3.2': 'látószög vizsgálata',
      '3.3.3': 'helymeghatározás koordináta-rendszerekben',
    },
  },
  {
    id: 'S',
    name: 'Statisztikai jellemzők, valószínűség',
    color: '#b45309',
    subs: {
      '4.1': 'statisztikai adatgyűjtés táblázatból/diagramról',
      '4.2': 'statisztikai adatábrázolás, adatok megfeleltetése',
      '4.3': 'statisztikai számítások (átlag, medián, terjedelem, gyakoriság)',
      '4.4': 'statisztikai módszerek (eljárás megadása, elemzése)',
      '4.5': 'valószínűség-számítás (biztos, lehetetlen, lehetséges események)',
      '4.6': 'kombinatorika (összeszámlálás)',
      '4.7': 'eseménygráfok (élek összeszámlálása, utak)',
      '4.8': 'halmazok (halmazműveletek)',
      '4.9': 'logikai ismeretek (logikai értékek, műveletek)',
    },
  },
];

export const THINKING_LEVELS = [
  {
    id: 'T',
    name: 'Tényismeret és egyszerű műveletek',
    short: 'Tényismeret',
    color: '#10b981',
    desc: 'Egy tartalmi területről származó egy vagy több egyértelmű lépés végrehajtása',
    subs: {
      '1.1': 'egyszerű matematikai definíciók, alapfogalmak felidézése; osztályozás',
      '1.2': 'adott tulajdonságú objektumok, ekvivalens objektumok azonosítása',
      '1.3': 'műveletek eredményének felismerése (pl. nézet, tükörkép, háló)',
      '1.4': 'számítások, műveletek végrehajtása (alapműveletek, képlet behelyettesítés)',
      '1.5': 'mérés, mértékegységek (leolvasás, mértékegység-átváltás ismert váltószámmal)',
      '1.6': 'adatgyűjtés leolvasással (grafikonról, táblázatból, skáláról)',
    },
  },
  {
    id: 'A',
    name: 'Alkalmazás, integráció',
    short: 'Alkalmazás',
    color: '#f59e0b',
    desc: 'Ismert módszerek vagy azok kombinációjának kiválasztása és alkalmazása',
    subs: {
      '2.1': 'jól definiált adatok megjelenítése, leolvasása, ábrázolása',
      '2.2': 'szabályok, összefüggések felismerése és alkalmazása',
      '2.3': 'ismert eljárások, algoritmusok kiválasztása és alkalmazása',
      '2.4': 'többféle eljárás, művelet és információ kombinálása',
    },
  },
  {
    id: 'K',
    name: 'Komplex megoldások és értékelés',
    short: 'Komplex',
    color: '#ef4444',
    desc: 'Komplex problémák megoldásai és az eredmények értékelése',
    subs: {
      '3.1': 'komolyabb értelmezést igénylő szituációban jellegzetességek felismerése, elemzése',
      '3.2': 'komolyabb értelmezést igénylő szituációban többféle művelet, információ kombinálása',
      '3.3': 'adatok megjelenítése, önálló ábrázolása',
      '3.4': 'műveletek végrehajtásával nyert adatok ábrázolása',
      '3.5': 'állítások, feltételezések érvényességének értékelése matematikai indoklással',
      '3.6': 'saját megoldási módszerek újszerű problémára',
    },
  },
];

export const TAXONOMY = { contentAreas: CONTENT_AREAS, thinkingLevels: THINKING_LEVELS };
