import { AdmissionTopic } from '../../../../data/admissionContent';
import { quizTortekEasy, quizTortekMedium, quizTortekHard } from './szamelmeletQuizzes';

export const szamelmeletTopic: AdmissionTopic = {
  id: "a-numbers",
  title: "2. Számelmélet és számok",
  icon: "🍕",
  color: "from-blue-500 to-blue-600",
  subtopics: [
    {
      id: "a-num-tortek",
      title: "Műveletek törtekkel",
      level: 0,
      requirements9th: "Végezzen közönséges törtekkel összeadást, kivonást (közös nevező), szorzást és osztást szabályosan.",
      requirements6th: "Tudjon törteket összeadni, kivonni, tizedes törtekkel alapműveleteket végezni.",
      requirements8th: "Értse a tört részeit és tudjon egyszerű törtekkel számolni.",
      lesson9th: `### Műveletek törtekkel\n\n- **Összeadás/Kivonás:** Közös nevezőre kell hozni a törteket!\n  $$\\frac{a}{b} \\pm \\frac{c}{d} = \\frac{a \\cdot d \\pm c \\cdot b}{b \\cdot d}$$\n- **Szorzás:** Számlálót a számlálóval, nevezőt a nevezővel szorozzuk: $\\frac{a}{b} \\cdot \\frac{c}{d} = \\frac{a \\cdot c}{b \\cdot d}$.\n- **Osztás:** Az osztót a reciprokával szorozzuk: $\\frac{a}{b} : \\frac{c}{d} = \\frac{a}{b} \\cdot \\frac{d}{c}$.`,
      lesson6th: `### Törtek összeadása, kivonása\n\nKözös nevezőre hozással: $\\frac{1}{2} + \\frac{1}{3} = \\frac{3}{6} + \\frac{2}{6} = \\frac{5}{6}$.`,
      lesson8th: `### Törtek alapjai\n\nA nevező megmutatja, hány egyenlő részre vágtuk az egészet, a számláló pedig, hogy hány részt vettünk belőle.`,
      quizEasy: quizTortekEasy,
      quizMedium: quizTortekMedium,
      quizHard: quizTortekHard
    },
    {
      id: "a-num-tizedestortek",
      title: "A tizedes törtek fajtái (véges, végtelen, végtelen szakaszos)",
      level: 1,
      requirements9th: "Csoportosítsa a tizedes törteket fajtájuk szerint. Tudja átírni a közönséges törtet tizedes törtté és fordítva.",
      requirements6th: "Ismerje a véges tizedes törtek fogalmát és végrehajtását.",
      requirements8th: "Értse az egyszerű tizedes tört formátumot (pl. 0.5, 0.25).",
      lesson9th: `### Tizedes törtek típusai\n\n- **Véges tizedes tört:** A tizedes jegyek száma véges (pl. $0,25 = 1/4$). Akkor keletkezik, ha a legegyszerűbb alakban lévő tört nevezőjének prímtényezős felbontásában csak a 2 és az 5 szerepel.\n- **Végtelen szakaszos tizedes tört:** A tizedes jegyek végtelenül ismétlődnek egy szakaszon (pl. $0,333\\dots = 0,\\dot{3} = 1/3$).\n- **Végtelen nem szakaszos:** Irracionális számok (pl. $\\pi, \\sqrt{2}$).`,
      lesson6th: `### Tizedes törtek tizedesjegyei\n\nTizedes tört közönséges törtté alakítása helyiérték alapján: $0,4 = 4/10 = 2/5$.`,
      lesson8th: `### Mi az a tizedes tört?\n\nA tizedes tört a tizes számrendszerben ábrázolja a törtrészt. Pl. $0,5 = \\text{öt tized} = 1/2$.`,
      quizEasy: quizTortekEasy,
      quizMedium: quizTortekMedium,
      quizHard: quizTortekHard
    },
    {
      id: "a-num-kerekites",
      title: "A kerekítés szabályainak alkalmazása",
      level: 1,
      requirements9th: "Alkalmazza magabiztosan a kerekítés szabályait tizedes törtekre és nagy számokra is.",
      requirements6th: "Kerekítsen tizedes törteket tizedre, századra.",
      requirements8th: "Kerekítsen egész számokat a megadott helyiértékre.",
      lesson9th: `### A kerekítés szabályai\n\nHa a kerekítendő helyiérték után álló számjegy:\n- $0, 1, 2, 3, 4$: lefelé kerekítünk (a jegy változatlan marad, utána 0-k állnak).\n- $5, 6, 7, 8, 9$: felfelé kerekítünk (a jegyet 1-gyel növeljük).\n\nPl. $23,546$ kerekítése századokra: $23,55$ (mivel a századok utáni jegy a 6).`,
      lesson6th: `### Kerekítés tizedekre\n\nPl. $3,45$ kerekítése tizedekre $3,5$ (mert a tizedek után az 5-ös áll).`,
      lesson8th: `### Kerekítés tizesekre, százasokra\n\nPl. 143 kerekítése tizesekre: 140. Kerekítése százasokra: 100.`,
      quizEasy: quizTortekEasy,
      quizMedium: quizTortekMedium,
      quizHard: quizTortekHard
    },
    {
      id: "a-num-hatvanyok",
      title: "Pozitív egész kitevőjű hatványok ismerete és műveletei",
      level: 1,
      requirements9th: "Alkalmazza a hatványozás azonosságait (azonos alapú/kitevőjű szorzás, osztás, hatvány hatványozása).",
      requirements6th: "Tudja a négyzet és köb fogalmát.",
      requirements8th: "Értse az egyszerű hatványokat (pl. 2 a harmadikon).",
      lesson9th: `### Hatványozás azonosságai\n\n- $a^n \\cdot a^m = a^{n+m}$\n- $a^n : a^m = a^{n-m}$\n- $(a^n)^m = a^{n \\cdot m}$\n- $(a \\cdot b)^n = a^n \\cdot b^n$\n- $(a/b)^n = a^n / b^n$`,
      lesson6th: `### Négyzet és köb\n\n- $a^2 = a \\cdot a$ (a a négyzeten)\n- $a^3 = a \\cdot a \\cdot a$ (a a köbön)`,
      lesson8th: `### Mi a hatványozás?\n\nAzonos tényezők szorzása. Pl. $2^3 = 2 \\cdot 2 \\cdot 2 = 8$.`,
      quizEasy: quizTortekEasy,
      quizMedium: quizTortekMedium,
      quizHard: quizTortekHard
    },
    {
      id: "a-num-rendszerek",
      title: "Számrendszerek ismerete",
      level: 1,
      requirements9th: "Írjon át számokat a tizes és a kettes (bináris) számrendszer között.",
      requirements6th: "Értse a helyiértékeket a tizes számrendszerben.",
      requirements8th: "Értse az egyesek, tizesek, százasok szerepét a számok felírásában.",
      lesson9th: `### Számrendszerek\n\n- **Tízes számrendszer:** Alapja a 10, helyiértékei: $1, 10, 100, 1000 \\dots$\n- **Kettes számrendszer:** Alapja a 2, helyiértékei jobbról balra: $1, 2, 4, 8, 16, 32 \\dots$ Pl. $1101_2 = 1 \\cdot 8 + 1 \\cdot 4 + 0 \\cdot 2 + 1 \\cdot 1 = 13_{10}$.`,
      lesson6th: `### Helyiérték táblázat\n\nPl. 452 = 4 százas + 5 tízes + 2 egyes.`,
      lesson8th: `### A tízes számrendszer\n\nTíz darab számjegyet használunk (0-9). Minden helyiérték az előző 10-szerese.`,
      quizEasy: quizTortekEasy,
      quizMedium: quizTortekMedium,
      quizHard: quizTortekHard
    },
    {
      id: "a-num-felbontas",
      title: "Összetett számok prímtényezős felbontása",
      level: 1,
      requirements9th: "Bontson fel összetett számokat prímek szorzatára.",
      requirements6th: "Ismerje a prímszámokat 20-ig.",
      requirements8th: "Értse meg a prímszám (törzsszám) fogalmát.",
      lesson9th: `### Prímtényezős felbontás\n\nMinden 1-nél nagyobb összetett szám egyértelműen felbontható prímszámok szorzatára. Pl. $90 = 2 \\cdot 3^2 \\cdot 5$.`,
      lesson6th: `### Prímszámok 20-ig\n\nPrímszámok: 2, 3, 5, 7, 11, 13, 17, 19.`,
      lesson8th: `### Mi a prímszám?\n\nAmelynek csak 1 és önmaga az osztója (pontosan két osztója van). A legkisebb prímszám a 2 (az egyetlen páros prím).`,
      quizEasy: quizTortekEasy,
      quizMedium: quizTortekMedium,
      quizHard: quizTortekHard
    },
    {
      id: "a-num-oszto",
      title: "Osztó",
      level: 1,
      requirements9th: "Határozza meg egy szám összes pozitív osztóját.",
      requirements6th: "Ismerje fel egy szám osztóit egyszerűbb esetekben.",
      requirements8th: "Értse az osztás és az osztó fogalmát.",
      lesson9th: `### Az osztó fogalma\n\nAz $a$ egész szám osztója a $b$ egész számnak, ha létezik olyan $k$ egész szám, hogy $b = a \\cdot k$. Pl. a 12 pozitív osztói: 1, 2, 3, 4, 6, 12.`,
      lesson6th: `### Osztók keresése\n\nPárokat keresünk: a 10 osztói: (1, 10) és (2, 5).`,
      lesson8th: `### Mi az osztó?\n\nHa elosztunk egy számot, és nincs maradék, akkor a számmal való osztás sikeres.`,
      quizEasy: quizTortekEasy,
      quizMedium: quizTortekMedium,
      quizHard: quizTortekHard
    },
    {
      id: "a-num-tobbszoros",
      title: "Többszörös",
      level: 1,
      requirements9th: "Határozza meg egy szám többszöröseit és vizsgálja az oszthatóságot.",
      requirements6th: "Képes legyen felsorolni egy szám első néhány többszörösét.",
      requirements8th: "Értse a többszörös fogalmát.",
      lesson9th: `### A többszörös fogalma\n\nEgy szám többszöröseit úgy kapjuk, hogy megszorozzuk egész számokkal. Pl. a 3 többszörösei: 3, 6, 9, 12, 15, 18...`,
      lesson6th: `### Szorzótábla és többszörösök\n\nA 4 többszörösei: 4, 8, 12, 16, 20...`,
      lesson8th: `### Mi a többszörös?\n\nHa egy számot megszorzol egy egész számmal, a szorzat a többszöröse lesz.`,
      quizEasy: quizTortekEasy,
      quizMedium: quizTortekMedium,
      quizHard: quizTortekHard
    },
    {
      id: "a-num-oszthatosag",
      title: "Oszthatósági szabályok (2, 3, 5, 9, 10, 100)",
      level: 1,
      requirements9th: "Alkalmazza magabiztosan az oszthatósági szabályokat elméleti és gyakorlati feladatokban.",
      requirements6th: "Ismerje a 2-vel, 5-tel, 10-zel való oszthatóságot.",
      requirements8th: "Értse a páros/páratlan számok és a 10-zel oszthatóság szabályát.",
      lesson9th: `### Oszthatósági szabályok\n\n- **2-vel:** utolsó számjegye 0, 2, 4, 6, 8.\n- **3-mal:** számjegyeinek összege osztható 3-mal.\n- **5-tel:** utolsó számjegye 0 vagy 5.\n- **9-cel:** számjegyeinek összege osztható 9-cel.\n- **10-zel:** utolsó számjegye 0.`,
      lesson6th: `### 2, 5, 10 oszthatósága\n\nUtolsó számjegy alapján döntünk!`,
      lesson8th: `### Páros és 10-es oszthatóság\n\nPáros számok végén: 0, 2, 4, 6, 8 áll.`,
      quizEasy: quizTortekEasy,
      quizMedium: quizTortekMedium,
      quizHard: quizTortekHard
    },
    {
      id: "a-num-lnko-lkkt",
      title: "Legnagyobb közös osztó (LNKO) és legkisebb közös többszörös (LKKT)",
      level: 1,
      requirements9th: "Számítsa ki két vagy több szám LNKO-ját és LKKT-jét prímtényezős felbontás segítségével.",
      requirements6th: "Keresse meg kis számok legkisebb közös többszörösét.",
      requirements8th: "Értse a közös osztó és közös többszörös alapjait.",
      lesson9th: `### LNKO és LKKT számítása\n\n1. Bontsuk fel a számokat prímhatványok szorzatára!\n2. **LNKO:** a közös prímalapok a *legkisebb* kitevőn.\n3. **LKKT:** az összes előforduló prímalap a *legnagyobb* kitevőn.`,
      lesson6th: `### Közös többszörösök\n\nSzámláljuk fel a többszörösöket és keressük a legkisebb közöset!`,
      lesson8th: `### Közös osztók\n\nKeressük meg a közös osztókat, a legnagyobb lesz az LNKO.`,
      quizEasy: quizTortekEasy,
      quizMedium: quizTortekMedium,
      quizHard: quizTortekHard
    }
  ]
};
