import { GraduationQuizQuestion } from '@/data/graduationContent';

// ============================================================================
// TOPIC 1: Gondolkodási módszerek, halmazok, logika, kombinatorika, gráfok
// ============================================================================

// --- 1. Halmazok (g-sets) ---
export const quizSetsEasy: GraduationQuizQuestion[] = [
  { id: "q-sets-e-1", question: "Ha $A = \\{1, 2, 3\\}$ és $B = \\{3, 4, 5\\}$, hány eleme van az uniójuknak ($A \\cup B$)?", options: ["5", "6", "3", "4"], correctAnswer: 0, explanation: "$A \\cup B = \\{1, 2, 3, 4, 5\\}$, ami 5 elem." },
  { id: "q-sets-e-2", question: "Melyik az üres halmaz jelölése?", options: ["$\\emptyset$", "$\\{0\\}$", "$0$", "$\\infty$"], correctAnswer: 0, explanation: "Az üres halmaz jele $\\emptyset$." },
  { id: "q-sets-e-3", question: "Ha $A = \\{2, 4, 6\\}$, hány eleme van $A$-nak?", options: ["3", "6", "2", "4"], correctAnswer: 0, explanation: "$A$ elemei: 2, 4, 6 (3 elem)." },
  { id: "q-sets-e-4", question: "Melyik kijelentés igaz az $A = \\{1, 5\\}$ és $B = \\{1, 3, 5, 7\\}$ halmazokra?", options: ["$A \\subseteq B$", "$B \\subseteq A$", "$A = B$", "$A \\cap B = \\emptyset$"], correctAnswer: 0, explanation: "$A$ minden eleme benne van $B$-ben, így $A \\subseteq B$." },
  { id: "q-sets-e-5", question: "Hány részhalmaza van egy 3 elemű halmaznak?", options: ["8", "6", "3", "9"], correctAnswer: 0, explanation: "$2^3 = 8$ részhalmaz." },
  { id: "q-sets-e-6", question: "Mi a 10 pozitív osztóinak halmaza?", options: ["$\\{1, 2, 5, 10\\}$", "$\\{2, 5\\}$", "$\\{1, 10\\}$", "$\\{1, 2, 4, 5, 10\\}$"], correctAnswer: 0, explanation: "10 osztói: 1, 2, 5, 10." },
  { id: "q-sets-e-7", question: "Mit jelent az $x \\in A$ jelölés?", options: ["x eleme az A halmaznak", "x részhalmaza A-nak", "x egyenlő A-val", "x nem eleme A-nak"], correctAnswer: 0, explanation: "Az $\\in$ az eleme kapcsolat jele." },
  { id: "q-sets-e-8", question: "Hány eleme van az üres halmaznak?", options: ["0", "1", "Végtelen", "Nem értelmezett"], correctAnswer: 0, explanation: "Az üres halmaznak 0 eleme van." },
  { id: "q-sets-e-9", question: "Melyik véges halmaz?", options: ["A 100-nál kisebb prímszámok halmaza", "A természetes számok halmaza", "A valós számok halmaza", "A racionális számok halmaza"], correctAnswer: 0, explanation: "A 100-nál kisebb prímek száma véges (25 db)." },
  { id: "q-sets-e-10", question: "Mi az $A = \\{a, b\\}$ és $B = \\{c, d\\}$ halmazok metszete?", options: ["$\\emptyset$", "$\\{a, b, c, d\\}$", "$\\{a, c\\}$", "$\\{0\\}$"], correctAnswer: 0, explanation: "Nincs közös elemük, így a metszetük az üres halmaz." }
];

export const quizSetsMedium: GraduationQuizQuestion[] = [
  { id: "q-sets-m-1", question: "Adott $U = \\{1..8\\}$ és $A = \\{2, 4, 6, 8\\}$. Mi az $A$ komplementere ($\\overline{A}$)?", options: ["$\\{1, 3, 5, 7\\}$", "$\\emptyset$", "$\\{2, 4\\}$", "$U$"], correctAnswer: 0, explanation: "$\\overline{A} = \\{1, 3, 5, 7\\}$." },
  { id: "q-sets-m-2", question: "Hány valódi részhalmaza van egy 4 elemű halmaznak?", options: ["15", "16", "14", "8"], correctAnswer: 0, explanation: "Összes részhalmaz: $2^4 = 16$. Valódi: $16 - 1 = 15$." },
  { id: "q-sets-m-3", question: "Ha $A \\subseteq B$, mennyi $A \\cap B$?", options: ["A", "B", "$\\emptyset$", "$A \\cup B$"], correctAnswer: 0, explanation: "Mivel $A \\subseteq B$, a metszetük $A$." },
  { id: "q-sets-m-4", question: "Ha $|A|=10, |B|=12, |A \\cap B|=4$, mennyi $|A \\cup B|$?", options: ["18", "22", "14", "26"], correctAnswer: 0, explanation: "$10 + 12 - 4 = 18$." },
  { id: "q-sets-m-5", question: "Melyik állítás ekvivalens az azzal, hogy $A \\setminus B = A$?", options: ["$A \\cap B = \\emptyset$", "$A = B$", "$A \\subseteq B$", "$B = \\emptyset$"], correctAnswer: 0, explanation: "A két halmaz diszjunkt." },
  { id: "q-sets-m-6", question: "Legyen $A = [-1, 4]$ és $B = (2, 6]$. Mi az $A \\cap B$ intervallum?", options: ["$(2, 4]$", "$[-1, 6]$", "$[-1, 2)$", "$[4, 6]$"], correctAnswer: 0, explanation: "Közös rész: $(2, 4]$." },
  { id: "q-sets-m-7", question: "Egy 30 fős osztályban 18-an angolul, 15-en németül tanulnak, 5-en egyiket sem. Hányan tanulnak mindkét nyelvet?", options: ["8", "5", "10", "3"], correctAnswer: 0, explanation: "$30 - 5 = 25$ nyelvet tanuló. $18 + 15 - 25 = 8$." },
  { id: "q-sets-m-8", question: "Hány 2-elemű részhalmaza van az $A = \\{1, 2, 3, 4, 5\\}$ halmaznak?", options: ["10", "20", "5", "25"], correctAnswer: 0, explanation: "$\\binom{5}{2} = 10$." },
  { id: "q-sets-m-9", question: "Hány eleme van az $A = \\{x \\in \\mathbb{Z} \\mid x^2 \\le 9\\}$ halmaznak?", options: ["7", "6", "3", "9"], correctAnswer: 0, explanation: "Elemei: $-3, -2, -1, 0, 1, 2, 3$ (7 elem)." },
  { id: "q-sets-m-10", question: "Mi az $A = \\{1, 2\\}$ halmaz hatványhalmazának elemeinek száma?", options: ["4", "2", "8", "3"], correctAnswer: 0, explanation: "$2^2 = 4$." }
];

export const quizSetsHard: GraduationQuizQuestion[] = [
  { id: "q-sets-h-1", question: "Mi a de Morgan I. szabálya $\\overline{A \\cap B}$-re?", options: ["$\\overline{A} \\cup \\overline{B}$", "$\\overline{A} \\cap \\overline{B}$", "$A \\cup B$", "$\\overline{A \\cup B}$"], correctAnswer: 0, explanation: "$\\overline{A \\cap B} = \\overline{A} \\cup \\overline{B}$." },
  { id: "q-sets-h-2", question: "Hány nemüres páros elemszámú részhalmaza van egy 5 elemű halmaznak?", options: ["15", "16", "31", "10"], correctAnswer: 0, explanation: "Páros elemszámúak száma $2^{5-1} = 16$. Üres halmaz kivételével: $16 - 1 = 15$." },
  { id: "q-sets-h-3", question: "Ha $|A| = 4$, hány eleme van $P(P(A))$-nak?", options: ["65536", "256", "16", "1024"], correctAnswer: 0, explanation: "$|P(A)| = 16 \\Rightarrow |P(P(A))| = 2^{16} = 65536$." },
  { id: "q-sets-h-4", question: "Három halmaz szita-formulájában hányszor vonjuk ki a három halmaz metszetét, ha a páronkénti metszeteket levonjuk?", options: ["Addig 3-szor levontuk, így 1-szer vissza kell adni (+)", "Nem vonjuk le", "Kétszer adjuk hozzá", "Négyszer vonjuk le"], correctAnswer: 0, explanation: "$|A \\cup B \\cup C| = \\sum|A| - \\sum|A \\cap B| + |A \\cap B \\cap C|$." },
  { id: "q-sets-h-5", question: "Milyen számosságú a valós számok halmaza ($\\mathbb{R}$)?", options: ["Kontinuum ($\\mathfrak{c}$)", "Megszámlálhatóan végtelen ($\\aleph_0$)", "Véges", "Nulla"], correctAnswer: 0, explanation: "Cantor tétele szerint a valós számok kontinuum számosságúak." },
  { id: "q-sets-h-6", question: "Ha $A_n = (0, 1/n)$ nyílt intervallum ($n \\in \\mathbb{N}^+$), mi a $\\bigcap_{n=1}^{\\infty} A_n$ metszet?", options: ["$\\emptyset$", "$\\{0\\}$", "$[0, 1]$", "$(0, 1)$"], correctAnswer: 0, explanation: "Egyetlen valós szám sincs benne az összes nyílt intervallumban, így üres halmaz." },
  { id: "q-sets-h-7", question: "Melyik halmazművelet felel meg a szimmetrikus különbségnek?", options: ["$(A \\setminus B) \\cup (B \\setminus A)$", "$A \\cap B$", "$A \\cup B$", "$A \\setminus B$"], correctAnswer: 0, explanation: "Ez a szimmetrikus különbség definíciója." },
  { id: "q-sets-h-8", question: "Ha $f: A \\to B$ bijekció és $|A| = 5$, mennyi $|B|$?", options: ["5", "10", "25", "1"], correctAnswer: 0, explanation: "Bijekciónál a halmazok elemszáma megegyezik." },
  { id: "q-sets-h-9", question: "Melyik állítás IGAZ az $A \\cap (B \\cup C)$ kifejezésre?", options: ["$(A \\cap B) \\cup (A \\cap C)$", "$(A \\cup B) \\cap (A \\cup C)$", "$A \\cap B \\cap C$", "$A \\cup B \\cup C$"], correctAnswer: 0, explanation: "Disztributivitás törvénye." },
  { id: "q-sets-h-10", question: "Mennyi az $A = \\{1, 2, 3\\}$ és $B = \\{a, b\\}$ Descartes-szorzatának elemszáma ($|A \\times B|$)?", options: ["6", "5", "9", "8"], correctAnswer: 0, explanation: "$3 \\cdot 2 = 6$." }
];

// --- 2. Halmazműveletek (g-set-operations) ---
export const quizSetOpsEasy: GraduationQuizQuestion[] = [
  { id: "q-so-e-1", question: "Mi az $A = \\{1, 2, 3\\}$ és $B = \\{2, 3, 4\\}$ metszete ($A \\cap B$)?", options: ["$\\{2, 3\\}$", "$\\{1, 2, 3, 4\\}$", "$\\{1, 4\\}$", "$\\emptyset$"], correctAnswer: 0, explanation: "Közös elemek: 2, 3." },
  { id: "q-so-e-2", question: "Mi az $A = \\{1, 2\\}$ és $B = \\{3, 4\\}$ uniója ($A \\cup B$)?", options: ["$\\{1, 2, 3, 4\\}$", "$\\emptyset$", "$\\{1, 3\\}$", "$\\{2, 4\\}$"], correctAnswer: 0, explanation: "Az unió tartalmazza az összes elemet: $\\{1, 2, 3, 4\\}$." },
  { id: "q-so-e-3", question: "Mi az $A = \\{1, 2, 3, 4\\}$ és $B = \\{3, 4, 5\\}$ különbsége ($A \\setminus B$)?", options: ["$\\{1, 2\\}$", "$\\{5\\}$", "$\\{3, 4\\}$", "$\\{1, 2, 5\\}$"], correctAnswer: 0, explanation: "Azok az A-beli elemek, amik B-ben nincsenek benne: $\\{1, 2\\}$." },
  { id: "q-so-e-4", question: "Adott $U = \\{1, 2, 3, 4, 5\\}$ és $A = \\{1, 3, 5\\}$. Mi az $A$ komplementere?", options: ["$\\{2, 4\\}$", "$\\{1, 3, 5\\}$", "$\\emptyset$", "$U$"], correctAnswer: 0, explanation: "$\\overline{A} = \\{2, 4\\}$." },
  { id: "q-so-e-5", question: "Melyik halmazművelet adja meg a két halmaz KÖZÖS elemeit?", options: ["Metszet ($\\cap$)", "Unió ($\\cup$)", "Különbség ($\\setminus$)", "Komplementer"], correctAnswer: 0, explanation: "A metszet a közös elemek halmaza." },
  { id: "q-so-e-6", question: "Ha $A \\cap B = \\emptyset$, hogy hívjuk az $A$ és $B$ halmazokat?", options: ["Diszjunkt halmazok", "Egyenlő halmazok", "Részhalmazok", "Komplementerek"], correctAnswer: 0, explanation: "Közös elem nélküli halmazok: diszjunktak." },
  { id: "q-so-e-7", question: "Mennyi $A \\cup \\emptyset$ értéke?", options: ["A", "$\\emptyset$", "$U$", "0"], correctAnswer: 0, explanation: "Bármely halmaz uniója az üres halmazzal önmaga." },
  { id: "q-so-e-8", question: "Mennyi $A \\cap \\emptyset$ értéke?", options: ["$\\emptyset$", "A", "$U$", "1"], correctAnswer: 0, explanation: "Bármely halmaz metszete az üres halmazzal üres." },
  { id: "q-so-e-9", question: "Ha $A = \\{1, 2, 3\\}$, mennyi $A \\setminus A$?", options: ["$\\emptyset$", "A", "$\\{0\\}$", "1"], correctAnswer: 0, explanation: "Ha egy halmazból kivonjuk önmagát, üres halmazt kapunk." },
  { id: "q-so-e-10", question: "Melyik szimbólum jelöli a halmazok unióját?", options: ["$\\cup$", "$\\cap$", "$\\setminus$", "$\\in$"], correctAnswer: 0, explanation: "Az unió jele a $\\cup$." }
];

export const quizSetOpsMedium: GraduationQuizQuestion[] = [
  { id: "q-so-m-1", question: "Legyen $A = \\{2, 3, 5, 7\\}$ és $B = \\{1, 3, 5, 9\\}$. Mi az $(A \\cup B) \\setminus (A \\cap B)$ halmaz?", options: ["$\\{1, 2, 7, 9\\}$", "$\\{3, 5\\}$", "$\\{1, 2, 3, 5, 7, 9\\}$", "$\\emptyset$"], correctAnswer: 0, explanation: "Unió: $\\{1..9\\}$, metszet: $\\{3, 5\\}$. Különbség: $\\{1, 2, 7, 9\\}$." },
  { id: "q-so-m-2", question: "Adott $U = \\{1..10\\}$, $A = \\{x \\mid x \\text{ páros}\\}$ és $B = \\{x \\mid x > 5\\}$. Mi az $\\overline{A \\cup B}$?", options: ["$\\{1, 3, 5\\}$", "$\\{2, 4\\}$", "$\\{6, 8, 10\\}$", "$\\emptyset$"], correctAnswer: 0, explanation: "$A \\cup B = \\{2,4,6,7,8,9,10\\}$. Ennek komplementere $U$-ban: $\\{1, 3, 5\\}$." },
  { id: "q-so-m-3", question: "Igaz-e, hogy $A \\setminus B = A \\cap \\overline{B}$?", options: ["Igaz", "Hamis", "Csak ha A és B diszjunkt", "Csak véges halmazokra"], correctAnswer: 0, explanation: "Ez a halmazkülönbség átírási szabálya." },
  { id: "q-so-m-4", question: "Ha $A = [0, 5]$ és $B = [3, 8]$, mi az $A \\setminus B$ intervallum?", options: ["$[0, 3)$", "$[0, 3]$", "$(5, 8]$", "$[3, 5]$"], correctAnswer: 0, explanation: "$[0, 5]$-ből elvéve a $[3, 8]$ részét $[0, 3)$ marad." },
  { id: "q-so-m-5", question: "Melyik azonosság fejezi ki a metszet kommutativitását?", options: ["$A \\cap B = B \\cap A$", "$A \\cap B = A \\cup B$", "$(A \\cap B) \\cap C = A \\cap (B \\cap C)$", "$A \\cap A = A$"], correctAnswer: 0, explanation: "Kommutativitás: a sorrend felcserélhető." },
  { id: "q-so-m-6", question: "Ha $A \\subseteq B$, mennyi $A \\setminus B$?", options: ["$\\emptyset$", "A", "B", "$B \\setminus A$"], correctAnswer: 0, explanation: "Ha A része B-nek, B kiveszi A minden elemét, így üres halmaz marad." },
  { id: "q-so-m-7", question: "Mennyi $\\overline{\\overline{A}}$ (a komplementer komplementere)?", options: ["A", "$\\overline{A}$", "$U$", "$\\emptyset$"], correctAnswer: 0, explanation: "Dupla tagadás / dupla komplementer az eredeti halmazt adja." },
  { id: "q-so-m-8", question: "Adott $A = \\{1, 2, 3\\}$. Hány eleme van az $A \\cap A$ metszetnek?", options: ["3", "6", "0", "1"], correctAnswer: 0, explanation: "$A \\cap A = A$, ami 3 elemű." },
  { id: "q-so-m-9", question: "Adott $A = \\{1, 2\\}, B = \\{2, 3\\}, C = \\{3, 4\\}$. Mi az $(A \\cup B) \\cap C$?", options: ["$\\{3\\}$", "$\\{2, 3\\}$", "$\\{1, 2, 3, 4\\}$", "$\\emptyset$"], correctAnswer: 0, explanation: "$A \\cup B = \\{1, 2, 3\\}$. Ennek metszete $C$-vel $\\{3\\}$." },
  { id: "q-so-m-10", question: "Mi az $A \\cup (A \\cap B)$ elnyelési tulajdonság eredménye?", options: ["A", "B", "$A \\cap B$", "$A \\cup B$"], correctAnswer: 0, explanation: "Elnyelési törvény: $A \\cup (A \\cap B) = A$." }
];

export const quizSetOpsHard: GraduationQuizQuestion[] = [
  { id: "q-so-h-1", question: "Melyik állítás ekvivalens a de Morgan II. szabályával: $\\overline{A \\cup B}$?", options: ["$\\overline{A} \\cap \\overline{B}$", "$\\overline{A} \\cup \\overline{B}$", "$A \\cap B$", "$\\overline{A \\setminus B}$"], correctAnswer: 0, explanation: "$\\overline{A \\cup B} = \\overline{A} \\cap \\overline{B}$." },
  { id: "q-so-h-2", question: "Bizonyítsuk az $A \\cap (B \\setminus C) = (A \\cap B) \\setminus C$ azonosságot! Igaz-e?", options: ["Igaz minden halmazra", "Hamis", "Csak ha C része A-nak", "Csak véges halmazokra"], correctAnswer: 0, explanation: "Mindkét oldal azokat az elemeket tartalmazza, melyek A-ban és B-ben benne vannak, de C-ben nincsenek." },
  { id: "q-so-h-3", question: "Legyen $A \\Delta B = (A \\setminus B) \\cup (B \\setminus A)$. Mennyi $A \\Delta A$?", options: ["$\\emptyset$", "A", "$U$", "2A"], correctAnswer: 0, explanation: "$A \\setminus A = \\emptyset$, így $\\emptyset \\cup \\emptyset = \\emptyset$." },
  { id: "q-so-h-4", question: "Legyen $A_k = [k, k+2]$ zárt intervallum ($k \\in \\mathbb{Z}$). Mi az $A_1 \\cap A_2$?", options: ["$[2, 3]$", "$[1, 4]$", "$[2, 2] = \\{2\\}$", "$\\emptyset$"], correctAnswer: 0, explanation: "$A_1 = [1, 3], A_2 = [2, 4]$. Metszetük $[2, 3]$." },
  { id: "q-so-h-5", question: "Ha $A \\cup B = U$ és $A \\cap B = \\emptyset$, mi a kapcsolat A és B között?", options: ["$B = \\overline{A}$", "$A = B$", "$A \\subseteq B$", "$B = \\emptyset$"], correctAnswer: 0, explanation: "B az A pontos komplementere U-ban." },
  { id: "q-so-h-6", question: "Mennyi az $(A \\setminus B) \\cap B$ metszet értéke?", options: ["$\\emptyset$", "A", "B", "$A \\cap B$"], correctAnswer: 0, explanation: "$A \\setminus B$ elemei nincsenek B-ben, így B-vel alkotott metszetük üres." },
  { id: "q-so-h-7", question: "Igaz-e a disztributivitás: $A \\cup (B \\cap C) = (A \\cup B) \\cap (A \\cup C)$?", options: ["Igaz", "Hamis", "Csak diszjunkt halmazokra", "Csak üres halmazra"], correctAnswer: 0, explanation: "Ez az unió disztributivitása a metszetre nézve." },
  { id: "q-so-h-8", question: "Melyik felel meg az $A \\subseteq B$ feltételnek komplementerekkel?", options: ["$\\overline{B} \\subseteq \\overline{A}$", "$\\overline{A} \\subseteq \\overline{B}$", "$\\overline{A} = \\overline{B}$", "$\\overline{A} \\cap \\overline{B} = U$"], correctAnswer: 0, explanation: "Kontrapozíció halmazelméletben: $A \\subseteq B \\Leftrightarrow \\overline{B} \\subseteq \\overline{A}$." },
  { id: "q-so-h-9", question: "Ha $|A \\Delta B| = 0$, mi mondható A-ról és B-ről?", options: ["$A = B$", "$A \\cap B = \\emptyset$", "$A \\cup B = U$", "$A \\subseteq B$"], correctAnswer: 0, explanation: "A szimmetrikus különbség 0 eleme jelentése: A és B teljesen megegyezik." },
  { id: "q-so-h-10", question: "Mi az $(A \\cap B) \\cup (A \\cap \\overline{B})$ kifejezés egyszerűsített alakja?", options: ["A", "B", "$A \\cap B$", "$U$"], correctAnswer: 0, explanation: "Disztributivitás visszafelé: $A \\cap (B \\cup \\overline{B}) = A \\cap U = A$." }
];

// --- 3. Számosság, részhalmazok (g-cardinality) ---
export const quizCardEasy: GraduationQuizQuestion[] = [
  { id: "q-ca-e-1", question: "Hány eleme van az $A = \\{3, 6, 9, 12\\}$ halmaznak?", options: ["4", "3", "12", "5"], correctAnswer: 0, explanation: "Elemei száma (számossága): 4." },
  { id: "q-ca-e-2", question: "Hány részhalmaza van egy 2 elemű halmaznak?", options: ["4", "2", "3", "8"], correctAnswer: 0, explanation: "$2^2 = 4$." },
  { id: "q-ca-e-3", question: "Mit jelent a $|A|$ jelölés halmazok esetén?", options: ["Az A halmaz elemeinek száma (számossága)", "Az A abszolút értéke", "Az A komplementere", "Az A uniója"], correctAnswer: 0, explanation: "A függőleges vonalak halmazoknál a számosságot jelölik." },
  { id: "q-ca-e-4", question: "Hány eleme van az üres halmaznak?", options: ["0", "1", "Végtelen", "-1"], correctAnswer: 0, explanation: "$|\\emptyset| = 0$." },
  { id: "q-ca-e-5", question: "Melyik halmaz megszámlálhatóan végtelen?", options: ["A természetes számok halmaza ($\\mathbb{N}$)", "A [0, 1] zárt intervallum", "Egy 10 elemű halmaz", "A valós számok halmaza"], correctAnswer: 0, explanation: "$\\mathbb{N}$ megszámlálhatóan végtelen számosságú." },
  { id: "q-ca-e-6", question: "Ha $A = \\{1, 2\\}$, melyik NEMSZÁMÍT részhalmazának?", options: ["$\\{1, 2, 3\\}$", "$\\emptyset$", "$\\{1\\}$", "$\\{1, 2\\}$"], correctAnswer: 0, explanation: "A $\\{1, 2, 3\\}$ több elemet tartalmaz, így nem lehet $A$ részhalmaza." },
  { id: "q-ca-e-7", question: "Hány 1-elemű részhalmaza van egy 4 elemű halmaznak?", options: ["4", "1", "6", "8"], correctAnswer: 0, explanation: "Minden egyedi elemből álló halmaz egy 1-elemű részhalmaz (4 db)." },
  { id: "q-ca-e-8", question: "Igaz-e, hogy az üres halmaz minden halmaznak részhalmaza?", options: ["Igaz", "Hamis", "Csak a véges halmazoknak", "Csak az üres halmaznak"], correctAnswer: 0, explanation: "Definíció szerint $\\emptyset \\subseteq A$ minden A halmazra." },
  { id: "q-ca-e-9", question: "Hány 0-elemű részhalmaza van egy halmaznak?", options: ["1 (az üres halmaz)", "0", "Végtelen", "Nincs ilyen"], correctAnswer: 0, explanation: "Egyetlen 0-elemű részhalmaz létezik: az üres halmaz." },
  { id: "q-ca-e-10", question: "Ha $|A| = 5$, hány eleme van az $A$ hatványhalmazának?", options: ["32", "10", "25", "64"], correctAnswer: 0, explanation: "$2^5 = 32$." }
];

export const quizCardMedium: GraduationQuizQuestion[] = [
  { id: "q-ca-m-1", question: "Hány valódi részhalmaza van egy 5 elemű halmaznak?", options: ["31", "32", "30", "16"], correctAnswer: 0, explanation: "$2^5 - 1 = 31$." },
  { id: "q-ca-m-2", question: "A szita-klauzula szerint ha $|A|=15, |B|=20, |A \\cup B|=28$, mennyi $|A \\cap B|$?", options: ["7", "5", "8", "12"], correctAnswer: 0, explanation: "$15 + 20 - 28 = 7$." },
  { id: "q-ca-m-3", question: "Hány 3-elemű részhalmaza van egy 6 elemű halmaznak?", options: ["20", "15", "18", "120"], correctAnswer: 0, explanation: "$\\binom{6}{3} = \\frac{6 \\cdot 5 \\cdot 4}{3 \\cdot 2 \\cdot 1} = 20$." },
  { id: "q-ca-m-4", question: "Ha $A$ és $B$ diszjunktak, $|A|=8$ és $|B|=6$, mennyi $|A \\cup B|$?", options: ["14", "48", "2", "0"], correctAnswer: 0, explanation: "Diszjunktaknál $|A \\cup B| = |A| + |B| = 8 + 6 = 14$." },
  { id: "q-ca-m-5", question: "Melyik halmaznak nagyobb a számossága: $\\mathbb{N}$ (természetes) vagy $\\mathbb{Z}$ (egészek)?", options: ["Egyenlő a számosságuk (mindkettő $\\aleph_0$)", "$\\mathbb{Z}$ nagyobb", "$\\mathbb{N}$ nagyobb", "Nem összehasonlítható"], correctAnswer: 0, explanation: "Kölcsönösen egyértelműen ráképezhetők egymásra, így számosságuk egyenlő ($\\aleph_0$)." },
  { id: "q-ca-m-6", question: "Hány olyan részhalmaza van az $A=\\{1, 2, 3, 4\\}$ halmaznak, ami tartalmazza az 1-es elemet?", options: ["8", "4", "16", "6"], correctAnswer: 0, explanation: "A maradék 3 elem részhalmazainak száma: $2^3 = 8$." },
  { id: "q-ca-m-7", question: "Egy 40 fős diákcsoportban 25-en sportolnak, 20-an zenélnek, 5-en egyiket sem. Hányan teszik mindkettőt?", options: ["10", "15", "5", "8"], correctAnswer: 0, explanation: "$40 - 5 = 35$ aktív. $25 + 20 - 35 = 10$." },
  { id: "q-ca-m-8", question: "Hány páratlan elemszámú részhalmaza van egy 4 elemű halmaznak?", options: ["8", "4", "6", "16"], correctAnswer: 0, explanation: "Összes részhalmaz fele páratlan elemszámú: $16 / 2 = 8$." },
  { id: "q-ca-m-9", question: "Ha $|A \\times B| = 12$ és $|A| = 3$, mennyi $|B|$?", options: ["4", "9", "36", "15"], correctAnswer: 0, explanation: "$|A \\times B| = |A| \\cdot |B| \\Rightarrow 12 = 3 \\cdot |B| \\Rightarrow |B| = 4$." },
  { id: "q-ca-m-10", question: "Hány elemű az $A = \\{x \\in \\mathbb{R} \\mid x^2 + 1 = 0\\}$ halmaz?", options: ["0", "2", "1", "Végtelen"], correctAnswer: 0, explanation: "Nincs valós megoldása az $x^2 = -1$-nek, így $A = \\emptyset$, aminek 0 eleme van." }
];

export const quizCardHard: GraduationQuizQuestion[] = [
  { id: "q-ca-h-1", question: "Bizonyítható-e Cantor átlós módszerével, hogy $\\mathbb{R}$ számossága nagyobb mint $\\mathbb{N}$-é?", options: ["Igen, ez a híres Cantor-tétel", "Nem, egyenlők", "Nem, N nagyobb", "Csak racionális számokra igaz"], correctAnswer: 0, explanation: "Cantor átlós eljárása igazolja, hogy a valós számok nem számlálhatók meg." },
  { id: "q-ca-h-2", question: "Hány olyan részhalmaza van egy 6 elemű halmaznak, amely legalább 4 elemet tartalmaz?", options: ["22", "15", "7", "32"], correctAnswer: 0, explanation: "$\\binom{6}{4} + \\binom{6}{5} + \\binom{6}{6} = 15 + 6 + 1 = 22$." },
  { id: "q-ca-h-3", question: "Milyen számosságú a racionális számok halmaza ($\\mathbb{Q}$)?", options: ["Megszámlálhatóan végtelen ($\\aleph_0$)", "Kontinuum", "Véges", "Végtelen de nem megszámlálható"], correctAnswer: 0, explanation: "Cantor első átlós módszerével igazolható, hogy $\\mathbb{Q}$ megszámlálható." },
  { id: "q-ca-h-4", question: "Ha $|A| = n$, mennyi a részhalmazok elemszámainak összege (összes részhalmaz elemszámának összege)?", options: ["$n \\cdot 2^{n-1}$", "$2^n$", "$n^2$", "$n!$"], correctAnswer: 0, explanation: "Minden elem $2^{n-1}$ részhalmazban szerepel, így az összeg $n \\cdot 2^{n-1}$." },
  { id: "q-ca-h-5", question: "Mi a kapcsolat egy $A$ halmaz és $P(A)$ hatványhalmaza számossága között?", options: ["$|A| < |P(A)|$ mindig igaz (Cantor-tétel)", "$|A| = |P(A)|$", "$|A| > |P(A)|$", "Csak véges halmazokra igaz"], correctAnswer: 0, explanation: "Cantor tétele szerint minden halmaz szigorúan kisebb számosságú a hatványhalmazánál." },
  { id: "q-ca-h-6", question: "Egy 100 fős évfolyamon 3 tantárgyi szakkör van. M=50, F=40, I=30. M∩F=20, M∩I=15, F∩I=10. Mindháromra 5-en járnak. Hányan nem járnak semelyikre?", options: ["20", "15", "10", "25"], correctAnswer: 0, explanation: "Unió: $(50+40+30)-(20+15+10)+5 = 120 - 45 + 5 = 80$. Semelyikre: $100 - 80 = 20$." },
  { id: "q-ca-h-7", question: "Melyik hiposztezis állítja, hogy nincs olyan számosság, amely szigorúan $\\aleph_0$ és $\\mathfrak{c}$ közé esik?", options: ["Kontinuum-hipotézis", "Fermat-hipotézis", "Riemann-hipotézis", "Goldbach-sejtés"], correctAnswer: 0, explanation: "Ez a híres Kontinuum-hipotézis (CH)." },
  { id: "q-ca-h-8", question: "Hány olyan nemüres részhalmaz pár $(A, B)$ képezhető egy 3 elemű halmazból, melyek diszjunktak ($A \\cap B = \\emptyset$)?", options: ["12", "27", "8", "18"], correctAnswer: 0, explanation: "Minden elemnél 3 lehetőség van: A-ban van, B-ben van, vagy egyikben sem ($3^3 = 27$). Levonva az üres halmazos eseteket." },
  { id: "q-ca-h-9", question: "Legyen $S$ egy $n$ elemű halmaz. Hány részhalmaz-pár $(A, B)$ létezik úgy, hogy $A \\subseteq B \\subseteq S$?", options: ["$3^n$", "$2^n$", "$4^n$", "$n!$"], correctAnswer: 0, explanation: "Minden elemre 3 lehetőség van: nincsen B-ben, B-ben van de A-ban nincs, A-ban és B-ben is benne van ($3^n$)." },
  { id: "q-ca-h-10", question: "Ha $A$ és $B$ megszámlálhatóan végtelen halmazok, milyen számosságú a Descartes-szorzatuk ($A \\times B$)?", options: ["Megszámlálhatóan végtelen ($\\aleph_0$)", "Kontinuum", "Véges", "Nem értelmezett"], correctAnswer: 0, explanation: "Két megszámlálható halmaz Descartes-szorzata is megszámlálhatóan végtelen." }
];

// --- 4. Matematikai logika (g-logic) ---
export const quizLogicEasy: GraduationQuizQuestion[] = [
  { id: "q-lo-e-1", question: "Mikor igaz a konjunkció ('és', $A \\land B$)?", options: ["Csak ha A és B is igaz", "Ha legalább az egyik igaz", "Ha mindkettő hamis", "Minden esetben"], correctAnswer: 0, explanation: "Az 'és' művelet csak akkor igaz, ha mindkét állítás igaz." },
  { id: "q-lo-e-2", question: "Mikor igaz a diszjunkció ('vagy', $A \\lor B$)?", options: ["Ha legalább az egyik állítás igaz", "Csak ha mindkettő igaz", "Csak ha az egyik igaz a másik hamis", "Soha nem igaz"], correctAnswer: 0, explanation: "A 'vagy' művelet akkor igaz, ha legalább az egyik tagja igaz." },
  { id: "q-lo-e-3", question: "Mi a negáció (tagadás, $\\neg A$) hatása az igazságértékre?", options: ["Az ellenkezőjére változtatja az igazságértéket", "Mindig igazzá teszi", "Mindig hamissá teszi", "Nem változtat rajta"], correctAnswer: 0, explanation: "A negáció felcseréli az igaz és hamis értéket." },
  { id: "q-lo-e-4", question: "Ha A igaz, akkor mi a $\\neg A$ igazságértéke?", options: ["Hamis", "Igaz", "Nem eldönthető", "Ismeretlen"], correctAnswer: 0, explanation: "Igaz állítás tagadása hamis." },
  { id: "q-lo-e-5", question: "Melyik kijelentés matematikai állítás (kijelentés)?", options: ["A 7 prímszám.", "Hány óra van?", "Tanulj szorgalmasan!", "Bár én is ott lennék."], correctAnswer: 0, explanation: "A 'A 7 prímszám' egy egyértelműen eldönthető kijelentés." },
  { id: "q-lo-e-6", question: "Mi a 'Minden páros szám osztható 2-vel' állítás tagadása?", options: ["Van olyan páros szám, ami nem osztható 2-vel.", "Egyetlen páros szám sem osztható 2-vel.", "Minden páratlan szám osztható 2-vel.", "A páros számok oszthatók 4-gyel."], correctAnswer: 0, explanation: "A 'minden' állítás tagadása: 'létezik legalább egy, amire nem igaz'." },
  { id: "q-lo-e-7", question: "Ha A hamis és B igaz, mi az $A \\land B$ értéke?", options: ["Hamis", "Igaz", "Ekvivalens", "Nincs értéke"], correctAnswer: 0, explanation: "Mivel A hamis, az 'és' művelet hamis." },
  { id: "q-lo-e-8", question: "Ha A hamis és B igaz, mi az $A \\lor B$ értéke?", options: ["Igaz", "Hamis", "Nem eldönthető", "Nulla"], correctAnswer: 0, explanation: "Mivel B igaz, a 'vagy' művelet igaz." },
  { id: "q-lo-e-9", question: "Mi a tautológia a matematikában?", options: ["Olyan összetett állítás, ami minden esetben IGAZ", "Olyan állítás, ami mindig HAMIS", "Egy téves bizonyítás", "Egy elgépelés"], correctAnswer: 0, explanation: "Tautológia az a logikai forma, ami minden igazságérték-kiosztás mellett igaz." },
  { id: "q-lo-e-10", question: "Melyik jelöli a logikai 'és' műveletet?", options: ["$\\land$", "$\\lor$", "$\\Rightarrow$", "$\\Leftrightarrow$"], correctAnswer: 0, explanation: "A konjunkció jele a $\\land$." }
];

export const quizLogicMedium: GraduationQuizQuestion[] = [
  { id: "q-lo-m-1", question: "Mikor HAMIS az $A \\Rightarrow B$ (implikáció)?", options: ["Ha A igaz és B hamis", "Ha A hamis és B igaz", "Ha A és B is hamis", "Ha A és B is igaz"], correctAnswer: 0, explanation: "Az implikáció egyetlen esetben hamis: ha az előtag igaz, de az utótag hamis." },
  { id: "q-lo-m-2", question: "Mikor IGAZ az $A \\Leftrightarrow B$ (ekvivalencia)?", options: ["Ha A és B igazságértéke megegyezik", "Csak ha mindkettő igaz", "Ha A igaz és B hamis", "Soha nem igaz"], correctAnswer: 0, explanation: "Az ekvivalencia akkor igaz, ha mindkettő igaz, vagy mindkettő hamis." },
  { id: "q-lo-m-3", question: "Mi az $A \\Rightarrow B$ implikáció kontrapozíciója?", options: ["$\\neg B \\Rightarrow \\neg A$", "$B \\Rightarrow A$", "$\\neg A \\Rightarrow \\neg B$", "$A \\land \\neg B$"], correctAnswer: 0, explanation: "A kontrapozíció $\\neg B \\Rightarrow \\neg A$, ami az eredeti implikációval logikailag ekvivalens." },
  { id: "q-lo-m-4", question: "Mi a 'Ha esik az eső, akkor vizes a csatorna' állítás megfordítása?", options: ["Ha vizes a csatorna, akkor esik az eső.", "Ha nem esik az eső, nem vizes a csatorna.", "Ha nem vizes a csatorna, nem esik az eső.", "Esik az eső és nem vizes a csatorna."], correctAnswer: 0, explanation: "Az implikáció megfordítása az előtag és utótag felcserélése: $B \\Rightarrow A$." },
  { id: "q-lo-m-5", question: "Melyik állítás ekvivalens az $A \\Rightarrow B$ implikációval?", options: ["$\\neg A \\lor B$", "$A \\land \\neg B$", "$\\neg A \\land B$", "$A \\lor B$"], correctAnswer: 0, explanation: "$A \\Rightarrow B$ logikailag megegyezik a $\\neg A \\lor B$ állítással." },
  { id: "q-lo-m-6", question: "Mi a de Morgan szabály a logikai konjunkció tagadására: $\\neg(A \\land B)$?", options: ["$\\neg A \\lor \\neg B$", "$\\neg A \\land \\neg B$", "$A \\lor B$", "$\\neg A \\Rightarrow \\neg B$"], correctAnswer: 0, explanation: "$\\neg(A \\land B) = \\neg A \\lor \\neg B$." },
  { id: "q-lo-m-7", question: "Ha A hamis, mi lesz az $A \\Rightarrow B$ implikáció igazságértéke?", options: ["Igaz (függetlenül B-től)", "Hamis", "B értéke határozza meg", "Nem értelmezett"], correctAnswer: 0, explanation: "Hamis előtagból bármi következik (az implikáció mindig igaz)." },
  { id: "q-lo-m-8", question: "Mi a 'Létezik olyan négyszög, amelyik nem tengelyesen szimmetrikus' kijelentés tagadása?", options: ["Minden négyszög tengelyesen szimmetrikus.", "Egyetlen négyszög sem tengelyesen szimmetrikus.", "Létezik szimmetrikus négyszög.", "Nincs ilyen négyszög."], correctAnswer: 0, explanation: "A 'létezik olyan, ami nem' tagadása: 'minden... az'." },
  { id: "q-lo-m-9", question: "Mi az $(A \\lor \\neg A)$ állítás igazságértéke?", options: ["Kizárt harmadik elve szerint mindig IGAZ (tautológia)", "Mindig HAMIS", "A-tól függ", "Nem eldönthető"], correctAnswer: 0, explanation: "Tertium non datur (kizárt harmadik elve): $A \\lor \\neg A$ mindig igaz." },
  { id: "q-lo-m-10", question: "Hány sora van egy 3 változós logikai igazságtáblának?", options: ["8", "6", "4", "16"], correctAnswer: 0, explanation: "$2^3 = 8$ lehetséges igazságérték-kombináció létezik." }
];

export const quizLogicHard: GraduationQuizQuestion[] = [
  { id: "q-lo-h-1", question: "Mi az $A \\Rightarrow B$ kijelentés tagadása?", options: ["$A \\land \\neg B$", "$\\neg A \\lor B$", "$\\neg A \\Rightarrow \\neg B$", "$B \\Rightarrow A$"], correctAnswer: 0, explanation: "$\\neg(A \\Rightarrow B) = \\neg(\\neg A \\lor B) = A \\land \\neg B$." },
  { id: "q-lo-h-2", question: "Legyen $A \\downarrow B$ a NOR (NAND/NOR) művelet (akkor igaz, ha mindkét tag hamis). Mivel ekvivalens $A \\downarrow A$?", options: ["$\\neg A$", "A", "True", "False"], correctAnswer: 0, explanation: "$\\neg(A \\lor A) = \\neg A$." },
  { id: "q-lo-h-3", question: "Melyik logikai műveletfelelet alkot teljes rendszert önmagában?", options: ["NAND (vagy NOR)", "AND", "OR", "IMPLICATION"], correctAnswer: 0, explanation: "A Sheffer-féle vonás (NAND) vagy a NOR művelet önmagában teljes rendszert alkot." },
  { id: "q-lo-h-4", question: "Mi a predikátumkalkulusban a $\\forall x P(x)$ állítás pontos tagadása?", options: ["$\\exists x \\neg P(x)$", "$\\forall x \\neg P(x)$", "$\\exists x P(x)$", "$\\neg \\forall x \\neg P(x)$"], correctAnswer: 0, explanation: "A univerzális kvantor tagadása az egzisztenciális kvantor a tagadott predikátumra." },
  { id: "q-lo-h-5", question: "Igaz-e a modallogika / klasszikus logika szabálya: $((A \\Rightarrow B) \\land (B \\Rightarrow C)) \\Rightarrow (A \\Rightarrow C)$?", options: ["Igaz (Hypothetical Syllogism - tranzitivitás)", "Hamis", "Csak ha A igaz", "Csak ha C hamis"], correctAnswer: 0, explanation: "Ez a hiporetikus szillogizmus tautológiája." },
  { id: "q-lo-h-6", question: "Melyik törvényt írja le az $A \\land (A \\lor B) \\equiv A$ formula?", options: ["Elnyelési törvény (Absorption law)", "Disztributivitás", "De Morgan törvény", "Asszociativitás"], correctAnswer: 0, explanation: "Ez a logikai elnyelési törvény." },
  { id: "q-lo-h-7", question: "Mi a kontradikció?", options: ["Olyan összetett állítás, ami minden igazságértékre HAMIS", "Mindig igaz állítás", "Formális bizonyítás", "Ekvivalens átalakítás"], correctAnswer: 0, explanation: "A kontradikció egy mindig hamis állítás (pl. $A \\land \\neg A$)." },
  { id: "q-lo-h-8", question: "Ha az $A \\Rightarrow B$ igaz és $B$ hamis, mit állíthatunk A-ról (Modus Tollens)?", options: ["A garantáltan HAMIS", "A igaz", "A lehet igaz vagy hamis", "Semmit"], correctAnswer: 0, explanation: "Modus Tollens: következmény hamisságából következik az előtag hamissága." },
  { id: "q-lo-h-9", question: "Ha az $A \\Rightarrow B$ és az $A$ is IGAZ, mit állíthatunk B-ről (Modus Ponens)?", options: ["B garantáltan IGAZ", "B hamis", "B tetszőleges", "A-tól függ"], correctAnswer: 0, explanation: "Modus Ponens: előtag igazságából és implikációból következik az utótag igazsága." },
  { id: "q-lo-h-10", question: "Hány olyan 2-változós logikai művelet létezik, amely tautológia vagy kontradikció nélkül felírható?", options: ["16 lehetséges logikai művelet van összesen 2 változóra", "4", "8", "32"], correctAnswer: 0, explanation: "Kétváltozós logikai igazságtáblázat $2^4 = 16$ különböző műveletet határoz meg." }
];

// --- 5. Fogalmak, tételek és bizonyítások (g-proofs) ---
export const quizProofsEasy: GraduationQuizQuestion[] = [
  { id: "q-pr-e-1", question: "Mi a definíció szerepe a matematikában?", options: ["Új fogalmak pontos bevezetése, megállapodás", "Igazolandó állítás megfogalmazása", "Egy számolási trükk", "Egy geometriai szerkesztés"], correctAnswer: 0, explanation: "A definíció egy új fogalom pontos meghatározása." },
  { id: "q-pr-e-2", question: "Mi a tétel a matematikában?", options: ["Olyan igaz állítás, amelyet bizonyítani kell", "Egy elfogadott megállapodás", "Egy matematikai jelölés", "Egy axióma"], correctAnswer: 0, explanation: "A tétel egy igazolásra szoruló igaz állítás." },
  { id: "q-pr-e-3", question: "Mi az axióma?", options: ["Bizonyítás nélkül elfogadott alapállítás", "Bizonyított tétel", "Definíció", "Egy számítási hiba"], correctAnswer: 0, explanation: "Az axiómák a matematikai elmélet bizonyítás nélkül elfogadott kiindulópontjai." },
  { id: "q-pr-e-4", question: "Mi a direkt bizonyítás lényege?", options: ["A feltételből kiindulva logikai lépésekkel eljutunk az állításig", "Ellentmondásra jutunk a tagadásból", "Példákkal szemléltetjük", "Méréseket végzünk"], correctAnswer: 0, explanation: "Direkt bizonyításnál a feltételekből egyenesen vezetjük le a célt." },
  { id: "q-pr-e-5", question: "Mi az indirekt bizonyítás lényege?", options: ["Feltesszük az állítás ellenkezőjét, és ellentmondásra jutunk", "Egyből bebizonyítjuk", "Kiszámoljuk számológéppel", "Nem bizonyítjuk be"], correctAnswer: 0, explanation: "Indirekt bizonyításnál a tagadásból kiindulva jutunk ellentmondásra." },
  { id: "q-pr-e-6", question: "Elég-e egy tétel igazolásához egyetlen jó példát mutatni?", options: ["Nem, egy példa nem bizonyítás!", "Igen, a példa bizonyít", "Csak geometriában elég", "Csak ha 100-nál nagyobb a szám"], correctAnswer: 0, explanation: "A matematikában a példa nem bizonyítás." },
  { id: "q-pr-e-7", question: "Mire jó az ellenpélda (cáfolat)?", options: ["Egy hamis állítás cáfolatára egyetlen ellenpélda is ELÉG", "Semmire nem jó", "Tételek bizonyítására", "Definíció alkotásra"], correctAnswer: 0, explanation: "Egy általános állítás cáfolásához egyetlen ellenpélda elegendő." },
  { id: "q-pr-e-8", question: "Melyik híres bizonyítási módszert használjuk egész számokra vonatkozó sorozatok igazolására?", options: ["Teljes indukció", "Pithagorasz-tétel", "Thalész-tétel", "Szinusztétel"], correctAnswer: 0, explanation: "A teljes indukció a természetes számokon értelmezett állítások bizonyítására szolgál." },
  { id: "q-pr-e-9", question: "Mi a skatulyaelv alapgondolata?", options: ["Ha n+1 tárgyat teszünk n skatulyába, legalább egyben több tárgy lesz", "A skatulyák száma mindig páros", "Minden tárgynak külön skatulya kell", "Nincs elég skatulya"], correctAnswer: 0, explanation: "Ez a Dirichlet-féle skatulyaelv." },
  { id: "q-pr-e-10", question: "Mit jelent a Q.E.D. (vagy a bizonyítás végén lévő kis négyzet $\\blacksquare$)?", options: ["Ezt kellett bizonyítani (Quod erat demonstrandum)", "Kérdés elvetve", "Gyors eredmény", "A tétel hamis"], correctAnswer: 0, explanation: "Q.E.D. = Quod erat demonstrandum (ezt kellett bizonyítani)." }
];

export const quizProofsMedium: GraduationQuizQuestion[] = [
  { id: "q-pr-m-1", question: "Hogyan bizonyítjuk indirekt módon, hogy a $\\sqrt{2}$ irracionális szám?", options: ["Feltesszük, hogy p/q alakú racionális szám, és ellentmondásra jutunk a simplified alak párosságánál", "Kiszámoljuk tizedestört alakban", "Méréssel", "Axiómákból levezetjük direkt módon"], correctAnswer: 0, explanation: "Ez a klasszikus pythagoreus indirekt bizonyítás." },
  { id: "q-pr-m-2", question: "Mi a teljes indukció 2 főlépése?", options: ["1. Bázislépés (n=1-re igaz) 2. Indukciós lépés (n-ről n+1-re igazolás)", "1. Kísérlet 2. Mérés", "1. Állítás 2. Példa", "1. Készítés 2. Ellenőrzés"], correctAnswer: 0, explanation: "A teljes indukció bázislépésből és indukciós lépésből áll." },
  { id: "q-pr-m-3", question: "Hány prímszám létezik a matematikában (Eukleidész tétele szerint)?", options: ["Végtelen sok (indirekt bizonyítással igazolható)", "Véges sok (1 milliárd)", "100 ezer", "Nem ismert"], correctAnswer: 0, explanation: "Eukleidész indirekt bizonyítással igazolta, hogy a prímek száma végtelen." },
  { id: "q-pr-m-4", question: "Skatulyaelv: Egy 13 fős társaságban van-e legalább két ember, aki ugyanabban a hónapban született?", options: ["Igen, garantáltan (13 ember, 12 hónap)", "Nem feltétlenül", "Soha", "Csak ha ikrek"], correctAnswer: 0, explanation: "13 tárgyat (ember) 12 skatulyába (hónap) téve a skatulyaelv miatt legalább 2 egybeesik." },
  { id: "q-pr-m-5", question: "Mi a szükséges és elégséges feltétel a matematikában?", options: ["Ekvivalens feltétel: A akkor és csak akkor teljesül, ha B teljesül", "A-ból nem következik B", "Csak geometriai tételekre érvényes", "Nincs különbség köztük"], correctAnswer: 0, explanation: "Szükséges és elégséges feltétel esetén a két állítás ekvivalens ($A \\Leftrightarrow B$)." },
  { id: "q-pr-m-6", question: "Ha az 'A szigorúan feltétele B-nek' ($B \\Rightarrow A$), akkor A a B-nek milyen feltétele?", options: ["Szükséges feltétele", "Elégséges feltétele", "Ekvivalens feltétele", "Nem feltétele"], correctAnswer: 0, explanation: "Ha B fennállásához A elengedhetetlen ($B \\Rightarrow A$), akkor A szükséges feltétel." },
  { id: "q-pr-m-7", question: "Ha $A \\Rightarrow B$, akkor A a B-nek milyen feltétele?", options: ["Elégséges feltétele", "Szükséges feltétele", "Nem feltétele", "Ekvivalens"], correctAnswer: 0, explanation: "Ha A teljesülése garantálja B-t ($A \\Rightarrow B$), akkor A elégséges feltétel." },
  { id: "q-pr-m-8", question: "Igaz-e az állítás: 'Ha egy szám osztható 4-gyel, akkor osztható 2-vel is'? Mi a tétel típusa?", options: ["Igaz állítás (direkt levezetés: 4k = 2(2k))", "Hamis állítás", "Indirekt állítás", "Axióma"], correctAnswer: 0, explanation: "A 4k felírható 2(2k) alakban, ami definíció szerint osztható 2-vel." },
  { id: "q-pr-m-9", question: "Mit jelent a konstruktív bizonyítás?", options: ["Megmutatjuk a keresett objektum konkrét előállítási módját / algoritmusát", "Megmutatjuk hogy nem létezik", "Indirekt módon bizonyítunk", "Grafikonon ábrázoljuk"], correctAnswer: 0, explanation: "A konstruktív bizonyítás megad egy konkrét példát vagy eljárást a létezésre." },
  { id: "q-pr-m-10", question: "Cáfolható-e az 'Minden páratlan szám prím' állítás ellenpéldával?", options: ["Igen, pl. a 9 páratlan de nem prím (3x3)", "Nem cáfolható", "Igen, a 2-vel", "Csak 100 felett"], correctAnswer: 0, explanation: "A 9 páratlan összetett szám egy tökéletes ellenpélda." }
];

export const quizProofsHard: GraduationQuizQuestion[] = [
  { id: "q-pr-h-1", question: "Bizonyítsuk a teljes indukciós hipotézissel: $\\sum_{k=1}^n k = \\frac{n(n+1)}{2}$. Mennyi az indukciós lépés hozzáadandó tagja $n+1$-re?", options: ["$n+1$", "$n$", "$\\frac{n+1}{2}$", "$2n$"], correctAnswer: 0, explanation: "$S_{n+1} = S_n + (n+1) = \\frac{n(n+1)}{2} + (n+1) = \\frac{(n+1)(n+2)}{2}$." },
  { id: "q-pr-h-2", question: "Melyik híres nem-konstruktív létezési bizonyítás használja az $a^b$ hatványt irracionális számokkal?", options: ["$\\sqrt{2}^{\\sqrt{2}}$ irracionális vagy racionális voltának esete", "Fermat utolsó tétele", "Gödel nemteljességi tétele", "Cantor-tétel"], correctAnswer: 0, explanation: "A $\\left(\\sqrt{2}^{\\sqrt{2}}\\right)^{\\sqrt{2}} = 2$ klasszikus nem-konstruktív bizonyítás." },
  { id: "q-pr-h-3", question: "Mit mondanak ki Gödel nemteljességi tételei (1931)?", options: ["Bármely ellentmondásmentes elegendő komplexitású axiómarendszerben vannak eldönthetetlen állítások", "Minden tétel bebizonyítható", "A matematika ellentmondásos", "A prímek végesek"], correctAnswer: 0, explanation: "Gödel I. nemteljességi tétele a korlátos formális rendszerekről." },
  { id: "q-pr-h-4", question: "Skatulyaelv geometriában: Egy $1 \\times 1$-es négyzetben elhelyezünk 5 pontot. Igazolható-e, hogy van kettő, amelyek távolsága $\\le \\frac{\\sqrt{2}}{2}$?", options: ["Igen, a négyzetet 4 darab $0.5 \\times 0.5$-es kis négyzetre osztva (skatulyák)", "Nem, nem igaz", "Csak 6 pontra igaz", "Nem dönthető el"], correctAnswer: 0, explanation: "4 kis négyzetbe 5 pontot téve legalább kettő egy kis négyzetbe kerül, átlójuk max $\\sqrt{0.5^2+0.5^2} = \\frac{\\sqrt{2}}{2}$." },
  { id: "q-pr-h-5", question: "Melyik az elégséges feltétele annak, hogy egy n fokszámú egyenletnek legyen valós gyöke az [a, b]-n?", options: ["f folytonos és f(a)*f(b) < 0 (Bolzano-tétel)", "f konvex", "f csökkenő", "f szimmetrikus"], correctAnswer: 0, explanation: "A Bolzano-tétel előjelváltás feltétele elégséges a gyök létezésére." },
  { id: "q-pr-h-6", question: "Mi a jól-rendezési elv a természetes számok halmazán ($\\mathbb{N}$)?", options: ["$\\mathbb{N}$ minden nemüres részhalmazának van legkisebb eleme", "Minden számnál van nagyobb", "A számok növekvő sorrendben vannak", "Minden részhalmaz véges"], correctAnswer: 0, explanation: "Ez a természetes számok jól-rendezettségi axiómája." },
  { id: "q-pr-h-7", question: "Mi a különbség a tétel megfordítása és a kontrapozíciója között?", options: ["A megfordítás ($B \\Rightarrow A$) nem mindig igaz, a kontrapozíció ($\\neg B \\Rightarrow \\neg A$) mindig ekvivalens az eredetivel", "Nincs különbség", "A kontrapozíció nem mindig igaz", "Mindkettő hamis"], correctAnswer: 0, explanation: "A tétel megfordítása független igazságértékű, míg a kontrapozíció az eredetivel ekvivalens." },
  { id: "q-pr-h-8", question: "Igazolható-e indukcióval, hogy $2^n > n$ minden $n \\in \\mathbb{N}^+$ esetén?", options: ["Igen, $n=1$-re $2 > 1$, és $2^{n+1} = 2 \\cdot 2^n > 2n \\ge n+1$", "Nem igaz", "Csak n>10-re igaz", "Csak páros n-re"], correctAnswer: 0, explanation: "Klasszikus teljes indukciós bizonyítás." },
  { id: "q-pr-h-9", question: "Mi a független axiómarendszer ismérve?", options: ["Egyetlen axiómája sem vezethető le a többi axiómából", "Minden axióma igaz", "Véges sok axiómából áll", "Nincs benne definíció"], correctAnswer: 0, explanation: "Függetlenség: semelyik axióma nem redundáns levezethető tétel." },
  { id: "q-pr-h-10", question: "Melyik geometria nem teljesíti Eukleidész V. párhuzamossági axiómáját?", options: ["Bolyai-Lobacsevszkij-féle hiperbolikus geometria", "Euklideszi geometria", "Síkgeometria", "Koordinátageometria"], correctAnswer: 0, explanation: "A nem-euklideszi (hiperbolikus/bolyai) geometriákban a párhuzamossági axióma nem teljesül." }
];

// --- 6. Kombinatorika (g-combinatorics) ---
export const quizCombEasy: GraduationQuizQuestion[] = [
  { id: "q-co-e-1", question: "Hányféleképpen ülhet le 3 ember egy padra (sorrend számít)?", options: ["6", "3", "9", "4"], correctAnswer: 0, explanation: "$3! = 3 \\cdot 2 \\cdot 1 = 6$ (Permutáció)." },
  { id: "q-co-e-2", question: "Mennyi 4! (4 faktoriális) értéke?", options: ["24", "12", "16", "10"], correctAnswer: 0, explanation: "$4! = 4 \\cdot 3 \\cdot 2 \\cdot 1 = 24$." },
  { id: "q-co-e-3", question: "Hányféleképpen választható ki 2 ember 5 közül, ha a sorrend NEMSZÁMÍT?", options: ["10", "20", "5", "15"], correctAnswer: 0, explanation: "Kombináció: $\\binom{5}{2} = \\frac{5 \\cdot 4}{2 \\cdot 1} = 10$." },
  { id: "q-co-e-4", question: "Hányféleképpen választható ki egy elnök és egy titkár 5 ember közül?", options: ["20", "10", "25", "12"], correctAnswer: 0, explanation: "Variáció: $5 \\cdot 4 = 20$ (sorrend számít!)." },
  { id: "q-co-e-5", question: "Mennyi 0! értéke a matematikában?", options: ["1", "0", "Nincs értelmezve", "Végtelen"], correctAnswer: 0, explanation: "Definíció szerint $0! = 1$." },
  { id: "q-co-e-6", question: "Hány 3-jegyű szám képezhető az 1, 2, 3 számjegyekből, ha a számjegyek ISMÉTELHETŐK?", options: ["27", "6", "9", "18"], correctAnswer: 0, explanation: "Ismétléses variáció: $3^3 = 27$." },
  { id: "q-co-e-7", question: "Hány 3-jegyű szám képezhető az 1, 2, 3 számjegyekből ismétlés NÉLKÜL?", options: ["6", "27", "9", "12"], correctAnswer: 0, explanation: "Permutáció: $3! = 6$." },
  { id: "q-co-e-8", question: "Mennyi $\\binom{5}{1}$ értéke?", options: ["5", "1", "10", "0"], correctAnswer: 0, explanation: "$\\binom{n}{1} = n$, így $\\binom{5}{1} = 5$." },
  { id: "q-co-e-9", question: "Mennyi $\\binom{5}{5}$ értéke?", options: ["1", "5", "25", "0"], correctAnswer: 0, explanation: "$\\binom{n}{n} = 1$." },
  { id: "q-co-e-10", question: "Melyik elv szerint szorozzuk össze a független döntési lehetőségek számát?", options: ["Kombinatorikai szorzási szabály", "Összeadási szabály", "Skatulyaelv", "Binomiális tétel"], correctAnswer: 0, explanation: "Egymástól független választásoknál a lehetőségek száma megszorzódik." }
];

export const quizCombMedium: GraduationQuizQuestion[] = [
  { id: "q-co-m-1", question: "Hányféleképpen rendezhető sorba az 'ALMA' szó betűi (ismétléses permutáció)?", options: ["12", "24", "6", "4"], correctAnswer: 0, explanation: "4 betű, 2 darab A: $\\frac{4!}{2!} = \\frac{24}{2} = 12$." },
  { id: "q-co-m-2", question: "A hatoslottón 6 számot húznak 45-ből. Hányféle kitöltés létezik?", options: ["$\\binom{45}{6} = 8\\ 145\\ 060$", "$45! / 6!$", "$45^6$", "$6^{45}$"], correctAnswer: 0, explanation: "Kombináció ismétlés nélkül: $\\binom{45}{6} = 8\\ 145\\ 060$." },
  { id: "q-co-m-3", question: "Hány átlója van egy konvex nyolcszögnek ($n = 8$)?", options: ["20", "28", "40", "16"], correctAnswer: 0, explanation: "Átlók száma: $\\frac{n(n-3)}{2} = \\frac{8 \\cdot 5}{2} = 20$." },
  { id: "q-co-m-4", question: "Mennyi a Pascal-háromszög 4. sorában lévő számok összege (1, 4, 6, 4, 1)?", options: ["16", "32", "8", "64"], correctAnswer: 0, explanation: "$2^4 = 16$ (az n-edik sor összege mindig $2^n$)." },
  { id: "q-co-m-5", question: "Hány olyan 4-jegyű páros szám van, amelynek minden számjegye különböző és nem tartalmazza a 0-t?", options: ["1344", "5000", "3024", "1000"], correctAnswer: 0, explanation: "Utolsó jegy 4-féle (2,4,6,8). Első 8-féle, második 7-féle, harmadik 6-féle: $4 \\cdot 8 \\cdot 7 \\cdot 6 = 1344$." },
  { id: "q-co-m-6", question: "Mennyi $\\binom{n}{k} + \\binom{n}{k+1}$ értéke a Pascal-háromszög azonossága szerint?", options: ["$\\binom{n+1}{k+1}$", "$\\binom{n+1}{k}$", "$\\binom{n}{k+2}$", "$\\binom{2n}{2k}$"], correctAnswer: 0, explanation: "Pascal-háromszög összeadási szabálya." },
  { id: "q-co-m-7", question: "Hányféleképpen osztható el 10 egyforma alma 3 gyerek között (ismétléses kombináció)?", options: ["$\\binom{12}{2} = 66$", "$\\binom{10}{3} = 120$", "$3^{10} = 59049$", "$10^3 = 1000$"], correctAnswer: 0, explanation: "Ismétléses kombináció: $\\binom{n+k-1}{k-1} = \\binom{10+3-1}{3-1} = \\binom{12}{2} = 66$." },
  { id: "q-co-m-8", question: "Hányféleképpen állítható fel 5 fiú és 5 lány egy sorba úgy, hogy a lányok és fiúk váltakozva álljanak?", options: ["28 800", "14 400", "3628800", "120"], correctAnswer: 0, explanation: "Két fő sorrend (F-L-F-L... vagy L-F-L-F...): $2 \\cdot 5! \\cdot 5! = 2 \\cdot 120 \\cdot 120 = 28\\ 800$." },
  { id: "q-co-m-9", question: "Mennyi az $(a+b)^4$ binomiális kifejtésében az $a^2 b^2$ tag együtthatója?", options: ["6", "4", "1", "12"], correctAnswer: 0, explanation: "$\\binom{4}{2} = 6$." },
  { id: "q-co-m-10", question: "Hány olyan 5-jegyű szám van a tizes számrendszerben, amely nem tartalmazza a 0 számjegyet?", options: ["$9^5 = 59049$", "$10^5 = 100000$", "$9 \\cdot 10^4 = 90000$", "$9! / 4!$"], correctAnswer: 0, explanation: "Minden pozíción 9-féle számjegy állhat (1..9): $9^5 = 59049$." }
];

export const quizCombHard: GraduationQuizQuestion[] = [
  { id: "q-co-h-1", question: "Hány olyan k-elemű részhalmaza van egy n-elemű halmaznak, ahol semelyik két elem nem szomszédos (sorszámban)?", options: ["$\\binom{n-k+1}{k}$", "$\\binom{n}{k}$", "$\\binom{n-k}{k}$", "$n! / k!$"], correctAnswer: 0, explanation: "Ez a híres Kaplansky-lemma sorkombinatorikában." },
  { id: "q-co-h-2", question: "Hányféleképpen helyezhető el 8 bástya egy 8x8-as sakktáblán úgy, hogy semelyik kettő ne üsse egymást?", options: ["8! = 40 320", "$8^8$", "$\\binom{64}{8}$", "64!"], correctAnswer: 0, explanation: "Minden oszlopban és sorban pontosan egy bástya állhat: $8! = 40320$." },
  { id: "q-co-h-3", question: "Mi az ismétléses permutációk száma az 'ABRACADABRA' (11 betű: 5A, 2B, 2R, 1C, 1D) szónál?", options: ["83 160", "39 916 800", "11!", "4620"], correctAnswer: 0, explanation: "$\\frac{11!}{5! \\cdot 2! \\cdot 2! \\cdot 1! \\cdot 1!} = \\frac{39916800}{120 \\cdot 2 \\cdot 2} = 83160$." },
  { id: "q-co-h-4", question: "Hány olyan zárójelezés létezik n pár zárójellel, ami helyes (Stirling/Catalan számok $C_n$)?", options: ["$C_n = \\frac{1}{n+1} \\binom{2n}{n}$", "$2^n$", "$n!$", "$\\binom{2n}{n}$"], correctAnswer: 0, explanation: "A helyes zárójelezések száma az n-edik Catalan-szám." },
  { id: "q-co-h-5", question: "Hány olyan zárt körút (Euler-kör) létezik egy n-pontú teljes gráfnál ($K_n$) irányítatlanul?", options: ["$\\frac{(n-1)!}{2}$ Hamilton-körökre", "$n!$", "$2^n$", "$\\binom{n}{2}$"], correctAnswer: 0, explanation: "Az irányítatlan Hamilton-körök száma $K_n$-ben $\\frac{(n-1)!}{2}$." },
  { id: "q-co-h-6", question: "Mennyi az $(x - 2)^6$ kifejtésében az $x^3$ együtthatója?", options: ["-160", "160", "-20", "240"], correctAnswer: 0, explanation: "Tag: $\\binom{6}{3} x^3 (-2)^3 = 20 \\cdot x^3 \\cdot (-8) = -160 x^3$." },
  { id: "q-co-h-7", question: "Hány olyan szigorúan monoton növekvő sorozat létezik, aminek elemei az $\\{1, 2, \\dots, 20\\}$ halmazból valók és 5 eleműek?", options: ["$\\binom{20}{5} = 15504$", "$20^5$", "$20! / 15!$", "$5^{20}$"], correctAnswer: 0, explanation: "Bármely 5 elem kiválasztásához pontosan 1 növekvő sorrend tartozik: $\\binom{20}{5}$." },
  { id: "q-co-h-8", question: "Mennyi a Stirling-féle másodfajú szám $S(n, k)$ jelentése?", options: ["Egy n-elemű halmaz k darab nemüres részhalmazra való felosztásainak száma", "Permutációk száma", "Kombinációk száma", "Faktoriálisok száma"], correctAnswer: 0, explanation: "A másodfajú Stirling-számok a halmazosztályozások számát adják meg." },
  { id: "q-co-h-9", question: "Hány olyan funkció $f: A \\to A$ létezik egy $n$-elemű halmazon, amely bijekció és egyetlen fixapontja sincs (derangement / zűrzavar)?", options: ["$D_n = n! \\sum_{k=0}^n \\frac{(-1)^k}{k!} \\approx \\frac{n!}{e}$", "$n! - 1$", "$2^n$", "$(n-1)!$"], correctAnswer: 0, explanation: "Fixpontmentes permutációk (zűrzavar) száma $D_n$." },
  { id: "q-co-h-10", question: "Hányféleképpen lehet 12 fős társaságot két 6 fős csapatra osztani?", options: ["$\\frac{1}{2} \\binom{12}{6} = 462$", "$\\binom{12}{6} = 924$", "$12! / 6!$", "$6^{12}$"], correctAnswer: 0, explanation: "Mivel a 2 csapat felcserélhető: $\\frac{1}{2} \\binom{12}{6} = \\frac{924}{2} = 462$." }
];

// --- 7. Gráfok (g-graphs) ---
export const quizGraphsEasy: GraduationQuizQuestion[] = [
  { id: "q-gr-e-1", question: "Hány éle van egy olyan gráfnak, amelyben a csúcsok fokszámainak összege 12?", options: ["6", "12", "24", "4"], correctAnswer: 0, explanation: "A fokszámösszeg-tétel szerint az élek száma a fokszámösszeg fele: $12 / 2 = 6$." },
  { id: "q-gr-e-2", question: "Hány éle van egy 5 pontú teljes gráfnak ($K_5$)?", options: ["10", "5", "20", "15"], correctAnswer: 0, explanation: "Teljes gráf éleinek száma: $\\binom{n}{2} = \\binom{5}{2} = 10$." },
  { id: "q-gr-e-3", question: "Hány éle van egy 6 csúcsú fa gráfnak?", options: ["5", "6", "15", "4"], correctAnswer: 0, explanation: "Egy $n$ csúcsú fának mindig $n - 1$ éle van: $6 - 1 = 5$." },
  { id: "q-gr-e-4", question: "Mit nevezünk egy csúcs fokszámának?", options: ["A belőle induló élek számát", "A csúcs sorszámát", "A gráf összes élének számát", "A gráf körinek számát"], correctAnswer: 0, explanation: "A csúcs fokszáma a hozzá illeszkedő élek száma." },
  { id: "q-gr-e-5", question: "Igaz-e, hogy egy gráfnál a páratlan fokszámú csúcsok száma mindig páros?", options: ["Igaz (Euler tétele miatt)", "Hamis", "Csak fákra igaz", "Csak teljes gráfra igaz"], correctAnswer: 0, explanation: "A fokszámösszeg páros (2e), ezért a páratlan tagok száma páros kell legyen." },
  { id: "q-gr-e-6", question: "Mi a fa gráf definíciója?", options: ["Összefüggő, körmentes gráf", "Olyan gráf amiben minden csúcs fokszáma 2", "Olyan gráf amiben van kör", "Teljes gráf"], correctAnswer: 0, explanation: "A fa egy összefüggő és körmentes gráf." },
  { id: "q-gr-e-7", question: "Hány csúcsa van egy 4 élt tartalmazó fa gráfnak?", options: ["5", "4", "3", "8"], correctAnswer: 0, explanation: "Mivel $e = n - 1 \\Rightarrow 4 = n - 1 \\Rightarrow n = 5$." },
  { id: "q-gr-e-8", question: "Hány fokszámú a K3 teljes gráf (háromszög gráf) minden csúcsa?", options: ["2", "3", "1", "0"], correctAnswer: 0, explanation: "Minden csúcs össze van kötve a másik 2 csúccsal, így fokszámuk 2." },
  { id: "q-gr-e-9", question: "Hogy nevezzük azt a gráfot, amelynek csúcsai között nincsenek élek?", options: ["Nullgráf (vagy üres gráf)", "Fa gráf", "Teljes gráf", "Páros gráf"], correctAnswer: 0, explanation: "Élek nélküli gráf a nullgráf." },
  { id: "q-gr-e-10", question: "Mi az hurokél?", options: ["Olyan él, amely önmagába tér vissza (ugyanazon csúcs mindkét végpontja)", "Két csúcsot összekötő él", "Párhuzamos él", "Hiányzó él"], correctAnswer: 0, explanation: "A hurokél önmagába visszatérő él." }
];

export const quizGraphsMedium: GraduationQuizQuestion[] = [
  { id: "q-gr-m-1", question: "Mikor tartalmaz egy gráf Euler-kört (minden élen pontosan egyszer áthaladó zárt séta)?", options: ["Ha összefüggő és minden csúcsának fokszáma PÁROS", "Ha fa gráf", "Ha nincs benne kör", "Ha teljes gráf"], correctAnswer: 0, explanation: "Euler tétele szerint az Euler-kör feltétele: összefüggőség + minden fokszám páros." },
  { id: "q-gr-m-2", question: "Hány éle van egy n-pontú komplementer gráfnak, ha az eredeti gráfnak e éle van?", options: ["$\\binom{n}{2} - e$", "$n! - e$", "$2n - e$", "$e^2$"], correctAnswer: 0, explanation: "A teljes gráf éleiből ($\\binom{n}{2}$) kivonjuk az eredeti éleket ($e$)." },
  { id: "q-gr-m-3", question: "Egy 6 pontú gráfnak a fokszámai: 2, 3, 3, 4, 4, 4. Hány éle van a gráfnak?", options: ["10", "20", "5", "12"], correctAnswer: 0, explanation: "Fokszámösszeg: $2 + 3 + 3 + 4 + 4 + 4 = 20$. Élek száma: $20 / 2 = 10$." },
  { id: "q-gr-m-4", question: "Mi a páros (bipartit) gráf ismérve?", options: ["A csúcsai 2 halmazba oszthatók úgy, hogy élek csak a két halmaz KÖZÖTT futnak", "Minden csúcs fokszáma páros", "Páros sok csúcsa van", "Fa gráf"], correctAnswer: 0, explanation: "Ez a bipartit (páros) gráf definíciója." },
  { id: "q-gr-m-5", question: "Igaz-e, hogy egy gráf akkor és csak akkor bipartit (páros), ha nem tartalmaz páratlan hosszúságú kört?", options: ["Igaz (Kőnig-tétel)", "Hamis", "Csak fákra igaz", "Csak síkgráfokra"], correctAnswer: 0, explanation: "Ez Kőnig tétele páros gráfokra." },
  { id: "q-gr-m-6", question: "Melyik állítás az Euler-féle síkgráf képlet egyszerű összefüggő síkgráfra ($c$ csúcs, $e$ él, $t$ tartomány)?", options: ["$c - e + t = 2$", "$c + e + t = 0$", "$c \\cdot e = t$", "$c - t = e$"], correctAnswer: 0, explanation: "Euler síkgráf formulája: $c - e + t = 2$." },
  { id: "q-gr-m-7", question: "Egy síkgráfnak 6 csúcsa és 9 éle van. Hány tartományra osztja a síkot?", options: ["5", "4", "6", "3"], correctAnswer: 0, explanation: "$c - e + t = 2 \\Rightarrow 6 - 9 + t = 2 \\Rightarrow -3 + t = 2 \\Rightarrow t = 5$." },
  { id: "q-gr-m-8", question: "Mikor nevezünk egy gráfot izomorgnak?", options: ["Ha csúcsaik között van olyan bijekció, ami megőrzi a szomszédosságot", "Ha azonos a csúcsaik száma", "Ha mindkettő fa", "Ha azonos az éleik száma"], correctAnswer: 0, explanation: "Az izomorfizmus a gráfok szerkezeti egyezését jelenti." },
  { id: "q-gr-m-9", question: "Hány éle van az $n=4$ pontú körelcsiknak ($C_4$)?", options: ["4", "6", "3", "8"], correctAnswer: 0, explanation: "A 4-körnek ($C_4$) 4 csúcsa és 4 éle van." },
  { id: "q-gr-m-10", question: "Mi a Hamilton-kör a gráfban?", options: ["Olyan zárt körút, amely a gráf MINDEN CSÚCSÁN pontosan egyszer halad át", "Minden élen áthaladó kör", "Egy fa gráf", "Egy legrövidebb út"], correctAnswer: 0, explanation: "Hamilton-kör: minden csúcsot pontosan egyszer érintő zárt körút." }
];

export const quizGraphsHard: GraduationQuizQuestion[] = [
  { id: "q-gr-h-1", question: "Melyik tétel ad elégséges feltételt Hamilton-kör létezésére (ha minden csúcs fokszáma $d(v) \\ge n/2$)?", options: ["Dirac-tétel", "Euler-tétel", "Kuratowski-tétel", "Cayley-tétel"], correctAnswer: 0, explanation: "Dirac tétele szerint ha $n \\ge 3$ és minden $d(v) \\ge n/2$, van Hamilton-kör." },
  { id: "q-gr-h-2", question: "Mi a Kuratowski-tétel síkgráfokra?", options: ["Egy gráf akkor és csak akkor síkgráf, ha nem tartalmaz $K_5$ vagy $K_{3,3}$ gráfalapú felosztást", "Minden fa síkgráf", "Minden gráf aminek $e \\le 3c-6$ az síkgráf", "Minden páros gráf síkgráf"], correctAnswer: 0, explanation: "Kuratowski híres tétele a $K_5$ és $K_{3,3}$ tiltott részgráfokról." },
  { id: "q-gr-h-3", question: "Hány különböző számozott fát lehet alkotni n csúcsból (Cayley-formula)?", options: ["$n^{n-2}$", "$n!$", "$2^n$", "$\\binom{n}{2}$"], correctAnswer: 0, explanation: "Cayley-formula: $n$ számozott csúcson $n^{n-2}$ különböző fa alkotható." },
  { id: "q-gr-h-4", question: "Melyik a négyszín-tétel állítása síkgráfokra?", options: ["Bármely síktérkép (síkgráf) színezhető legfeljebb 4 színnel úgy, hogy szomszédos tartományok ne legyenek azonos színűek", "Minden gráf 4-színezhető", "Csak a fák színezhetők 4 színnel", "A teljes gráfok 4-színezhetők"], correctAnswer: 0, explanation: "A híres Négyszín-tétel (Appel & Haken, 1976)." },
  { id: "q-gr-h-5", question: "Mennyi a maximális élek száma egy $n$ csúcsú egyszerű síkgráfban ($n \\ge 3$)?", options: ["$3n - 6$", "$n(n-1)/2$", "$2n - 4$", "$n^2$"], correctAnswer: 0, explanation: "Síkgráfban a maximális élszám $e \\le 3n - 6$." },
  { id: "q-gr-h-6", question: "Melyik alábbi gráf NEM síkba rajzolható (nem síkgráf)?", options: ["$K_5$ (5 pontú teljes gráf)", "$K_4$", "C5 (5-kör)", "Q3 (kockagrál)"], correctAnswer: 0, explanation: "$K_5$ a legkisebb nem-síkgráf." },
  { id: "q-gr-h-7", question: "Mi a gráf kromatikus száma ($\\chi(G)$)?", options: ["A minimális színek száma, amivel a csúcsok jólszínezhetők", "Az élek száma", "A maximális fokszám", "A tartományok száma"], correctAnswer: 0, explanation: "$\\chi(G)$ a csúcsszínezési szám." },
  { id: "q-gr-h-8", question: "Mennyi a $K_{n, m}$ teljes páros gráf éleinek száma?", options: ["$n \\cdot m$", "$n + m$", "$\\binom{n+m}{2}$", "$2nm$"], correctAnswer: 0, explanation: "Minden n-beli csúcs össze van kötve minden m-beli csúccsal: $n \\cdot m$ él." },
  { id: "q-gr-h-9", question: "Mi az Ore-tétel Hamilton-körre?", options: ["Ha bármely két nem szomszédos csúcs fokszámösszege $d(u) + d(v) \\ge n$, van Hamilton-kör", "Ha a gráf fa", "Ha minden fokszám páros", "Ha c > 10"], correctAnswer: 0, explanation: "Ore tétele a nem szomszédos csúcsok fokszámösszegéről." },
  { id: "q-gr-h-10", question: "Mi a feszítőfa (spanning tree) egy összefüggő gráfban?", options: ["Olyan részgráf, amely fa és a gráf MINDEN csúcsát tartalmazza", "A legrövidebb kör", "A leghosszabb út", "Egy teljes részgráf"], correctAnswer: 0, explanation: "A feszítőfa a gráf összes csúcsát tartalmazó fa részgráf." }
];

// Map containing dedicated quizzes for every subtopic in Gondolkodási módszerek
export const gondolkodasiQuizzes: Record<string, { easy: GraduationQuizQuestion[]; medium: GraduationQuizQuestion[]; hard: GraduationQuizQuestion[] }> = {
  'g-sets': { easy: quizSetsEasy, medium: quizSetsMedium, hard: quizSetsHard },
  'g-set-operations': { easy: quizSetOpsEasy, medium: quizSetOpsMedium, hard: quizSetOpsHard },
  'g-cardinality': { easy: quizCardEasy, medium: quizCardMedium, hard: quizCardHard },
  'g-logic': { easy: quizLogicEasy, medium: quizLogicMedium, hard: quizLogicHard },
  'g-proofs': { easy: quizProofsEasy, medium: quizProofsMedium, hard: quizProofsHard },
  'g-combinatorics': { easy: quizCombEasy, medium: quizCombMedium, hard: quizCombHard },
  'g-graphs': { easy: quizGraphsEasy, medium: quizGraphsMedium, hard: quizGraphsHard }
};
